value= 
options=[
    how about you deliver this to <ENEMY_WORK_CONTACT> GIVE <BOMB>
]
options_to_state_uuid_to_attribute_mod={
    how about you deliver this to <ENEMY_WORK_CONTACT> GIVE <BOMB>={
        2fdd0dd1-f1e0-460b-a9d6-3067441e034b=[
            {
                attribute=happiness_mood
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    how about you deliver this to <ENEMY_WORK_CONTACT> GIVE <BOMB>={
        2fdd0dd1-f1e0-460b-a9d6-3067441e034b=how about you deliver this to <ENEMY_WORK_CONTACT> GIVE <BOMB>
    }
}
