value=<NPC_NAME>
options=[
    oh that's right! the handsome man that took me for a stroll last evening
]
options_to_state_uuid_to_attribute_mod={
    oh that's right! the handsome man that took me for a stroll last evening={
        3a2c8345-9f87-4705-bcbc-52a1398f7972=[
        ]
    }
}
options_to_state_uuid_response={
    oh that's right! the handsome man that took me for a stroll last evening={
        3a2c8345-9f87-4705-bcbc-52a1398f7972=oh that's right! the handsome man that took me for a stroll last evening
    }
}
