value=<VALUABLE_ITEM> mostly
options=[
    hmm, you'll have to check out the market then i guess
]
options_to_state_uuid_to_attribute_mod={
    hmm, you'll have to check out the market then i guess={
        c63f0104-8deb-4c01-9119-94b39a89e3d7=[
        ]
    }
}
options_to_state_uuid_response={
    hmm, you'll have to check out the market then i guess={
        c63f0104-8deb-4c01-9119-94b39a89e3d7=hmm, you'll have to check out the market then i guess
    }
}
