value=a grandpa!
options=[
    ok sure
    you're a grandpa?
]
options_to_state_uuid_to_attribute_mod={
    you're a grandpa?={
        aeae5ae1-8d98-4479-91d4-3f29ef19a3fb=[
        ]
    }
    ok sure={
        e3200da8-b9f0-4a28-9c51-3230aea52399=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    you're a grandpa?={
        aeae5ae1-8d98-4479-91d4-3f29ef19a3fb=you're a grandpa?
    }
    ok sure={
        e3200da8-b9f0-4a28-9c51-3230aea52399=ok sure
    }
}
