value=ah come on! it's good!...ish i guess
options=[
    no thanks, though do you have any new goods for the shop?
]
options_to_state_uuid_to_attribute_mod={
    no thanks, though do you have any new goods for the shop?={
        7c4b2d0c-1223-4671-8772-561b7c5a5d8a=[
        ]
    }
}
options_to_state_uuid_response={
    no thanks, though do you have any new goods for the shop?={
        7c4b2d0c-1223-4671-8772-561b7c5a5d8a=no thanks, though do you have any new goods for the shop?
    }
}
