value=ah man ok, well at least tell me something funny
options=[
    ok well, let me think
]
options_to_state_uuid_to_attribute_mod={
    ok well, let me think={
        c47ab99f-618c-4cbc-a9c5-ad8033c41876=[
            {
                attribute=trust
                amount=-0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    ok well, let me think={
        c47ab99f-618c-4cbc-a9c5-ad8033c41876=ok well, let me think
    }
}
