value=all good! what you have been up to?
options=[
    oh i've been <RECENT_ACTIVITY>
]
options_to_state_uuid_to_attribute_mod={
    oh i've been <RECENT_ACTIVITY>={
        6ce49061-1552-4899-8d7a-1aac039df62b=[
            {
                attribute=friendship
                amount=0.2
            }
        ]
    }
}
options_to_state_uuid_response={
    oh i've been <RECENT_ACTIVITY>={
        6ce49061-1552-4899-8d7a-1aac039df62b=oh i've been <RECENT_ACTIVITY>
    }
}
