value=all's well father
options=[
    oh good, it always pleases me to here that
]
options_to_state_uuid_to_attribute_mod={
    oh good, it always pleases me to here that={
        64eba1d1-2c7c-438a-9f74-63e4c1c14ef3=[
        ]
    }
}
options_to_state_uuid_response={
    oh good, it always pleases me to here that={
        64eba1d1-2c7c-438a-9f74-63e4c1c14ef3=oh good, it always pleases me to here that
    }
}
