value=as do i, a fare lady is hard to come by
options=[
    oh yes I suppose
]
options_to_state_uuid_to_attribute_mod={
    oh yes I suppose={
        3a7c6f68-b2a1-4181-8f6f-6a6996f58cb5=[
            {
                attribute=romance
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    oh yes I suppose={
        3a7c6f68-b2a1-4181-8f6f-6a6996f58cb5=oh yes I suppose
    }
}
