value=aye, though i do feel a little better now
options=[
    it's the food isn't it!
]
options_to_state_uuid_to_attribute_mod={
    it's the food isn't it!={
        4cb5d623-8bcc-47fa-b668-2b03ffde1c73=[
            {
                attribute=happiness_mood
                amount=1
            }
        ]
    }
}
options_to_state_uuid_response={
    it's the food isn't it!={
        4cb5d623-8bcc-47fa-b668-2b03ffde1c73=it's the food isn't it!
    }
}
