value=can you do it for me?
options=[
    ok no, but I can help you
    yeah sure one sec
]
options_to_state_uuid_to_attribute_mod={
    yeah sure one sec={
        4966a6ad-9771-4842-be24-1527aa1da4f8=[
        ]
    }
    ok no, but I can help you={
        74f05ca6-4fc8-468b-8149-a8f13dd9c542=[
        ]
    }
}
options_to_state_uuid_response={
    yeah sure one sec={
        4966a6ad-9771-4842-be24-1527aa1da4f8=yeah sure one sec
    }
    ok no, but I can help you={
        74f05ca6-4fc8-468b-8149-a8f13dd9c542=ok no, but I can help you
    }
}
