value=can't you go get some?
options=[
    or you could go get me a <PET_ANIMAL>?
]
options_to_state_uuid_to_attribute_mod={
    or you could go get me a <PET_ANIMAL>?={
        2de0d496-4174-405c-a64f-c8968b8149a8=[
        ]
    }
}
options_to_state_uuid_response={
    or you could go get me a <PET_ANIMAL>?={
        2de0d496-4174-405c-a64f-c8968b8149a8=or you could go get me a <PET_ANIMAL>?
    }
}
