value=care to join me for stroll?
options=[
    i suppose i could
]
options_to_state_uuid_to_attribute_mod={
    i suppose i could={
        6f68b2a1-1181-4f6f-aa69-96f58cb5cfea=[
            {
                attribute=romance
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    i suppose i could={
        6f68b2a1-1181-4f6f-aa69-96f58cb5cfea=i suppose i could
    }
}
