value=care to pass some time with an old woman?
options=[
    i don't have time
    what haha
]
options_to_state_uuid_to_attribute_mod={
    what haha={
        6a12cbfc-4b8f-4a8f-bb7d-e3200da8b9f0=[
            {
                attribute=happiness_mood
                amount=0.1
            }
        ]
    }
    i don't have time={
        5bcc5a05-ac07-4eb8-8198-655f4bbcf431=[
            {
                attribute=friendship
                amount=-0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    what haha={
        6a12cbfc-4b8f-4a8f-bb7d-e3200da8b9f0=what haha
    }
    i don't have time={
        5bcc5a05-ac07-4eb8-8198-655f4bbcf431=i don't have time
    }
}
