value=cracking down on wimps
options=[
    cracking down on wimps? haha, wait what did you do?
]
options_to_state_uuid_to_attribute_mod={
    cracking down on wimps? haha, wait what did you do?={
        238bccc7-fa36-482b-83ff-de1c737ce064=[
            {
                attribute=happiness_mood
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    cracking down on wimps? haha, wait what did you do?={
        238bccc7-fa36-482b-83ff-de1c737ce064=cracking down on wimps? haha, wait what did you do?
    }
}
