value=cracking down on wimps? haha, wait what did you do?
options=[
    oh you know, help understand things
]
options_to_state_uuid_to_attribute_mod={
    oh you know, help understand things={
        8bccc7fa-3668-4b03-bfde-1c737ce064ee=[
        ]
    }
}
options_to_state_uuid_response={
    oh you know, help understand things={
        8bccc7fa-3668-4b03-bfde-1c737ce064ee=oh you know, help understand things
    }
}
