value=daughter haha
options=[
    oh you old fellow! where have you been all this time
]
options_to_state_uuid_to_attribute_mod={
    oh you old fellow! where have you been all this time={
        8c55f22c-9687-408d-9c37-0fa75b07be94=[
            {
                attribute=romance
                amount=0.4
            }
        ]
    }
}
options_to_state_uuid_response={
    oh you old fellow! where have you been all this time={
        8c55f22c-9687-408d-9c37-0fa75b07be94=oh you old fellow! where have you been all this time
    }
}
