value=do you need some help?
options=[
    no but a cute young man would be nice
    sure
]
options_to_state_uuid_to_attribute_mod={
    sure={
        8cfe68a6-2fdd-4dd1-b1e0-d60b29d63067=[
        ]
    }
    no but a cute young man would be nice={
        cd432251-e772-486c-aa54-d74035c641f0=[
        ]
    }
}
options_to_state_uuid_response={
    sure={
        8cfe68a6-2fdd-4dd1-b1e0-d60b29d63067=sure
    }
    no but a cute young man would be nice={
        cd432251-e772-486c-aa54-d74035c641f0=no but a cute young man would be nice
    }
}
