value=don't worry about it
options=[
    hey could you introduce me to one of your high up friends?
]
options_to_state_uuid_to_attribute_mod={
    hey could you introduce me to one of your high up friends?={
        ab690a03-ca5a-4fdb-9753-8570c77e60f3=[
            {
                attribute=trust
                amount=-0.2
            }
        ]
    }
}
options_to_state_uuid_response={
    hey could you introduce me to one of your high up friends?={
        ab690a03-ca5a-4fdb-9753-8570c77e60f3=hey could you introduce me to one of your high up friends?
    }
}
