value=fair enough for my own needs. though hungry
options=[
    here have this GIVE <FOOD>
]
options_to_state_uuid_to_attribute_mod={
    here have this GIVE <FOOD>={
        dd9f74b6-2427-40c5-aac3-2af8e8e763bb=[
            {
                attribute=trust
                amount=-0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    here have this GIVE <FOOD>={
        dd9f74b6-2427-40c5-aac3-2af8e8e763bb=here have this GIVE <FOOD>
    }
}
