value=father, why don't you make us a ship sometime
options=[
    hmm, i guess i could do that. i'm rather handy
]
options_to_state_uuid_to_attribute_mod={
    hmm, i guess i could do that. i'm rather handy={
        a1d12c7c-e38a-4f74-a3e4-c1c14ef3e8f4=[
        ]
    }
}
options_to_state_uuid_response={
    hmm, i guess i could do that. i'm rather handy={
        a1d12c7c-e38a-4f74-a3e4-c1c14ef3e8f4=hmm, i guess i could do that. i'm rather handy
    }
}
