value=FIGHT
options=[
    RUN
    hey no hitting little one
    stop it
]
options_to_state_uuid_to_attribute_mod={
    stop it={
        da71b8a8-e0f0-4605-ac70-0ca82906918b=[
        ]
    }
    hey no hitting little one={
        794dda71-b8a8-40f0-8605-ec700ca82906=[
            {
                attribute=anxiety_mood
                amount=0.1
            }
        ]
    }
    RUN={
        d47951d4-3f29-4f19-a3fb-18606504c858=[
            {
                attribute=anxiety_mood
                amount=3
            }
        ]
    }
}
options_to_state_uuid_response={
    stop it={
        da71b8a8-e0f0-4605-ac70-0ca82906918b=stop it
    }
    hey no hitting little one={
        794dda71-b8a8-40f0-8605-ec700ca82906=hey no hitting little one
    }
    RUN={
        d47951d4-3f29-4f19-a3fb-18606504c858=RUN
    }
}
