value=FOLLOW
options=[
    ok here it is! GIVE <FOOD>
    GO_TO <FUN_PLACE>
]
options_to_state_uuid_to_attribute_mod={
    GO_TO <FUN_PLACE>={
        37946adf-8305-45ff-9e95-25ccfdceba22=[
        ]
    }
    ok here it is! GIVE <FOOD>={
        9771e842-3e24-4527-aa1d-a4f873972d9f=[
        ]
    }
}
options_to_state_uuid_response={
    GO_TO <FUN_PLACE>={
        37946adf-8305-45ff-9e95-25ccfdceba22=GO_TO <FUN_PLACE>
    }
    ok here it is! GIVE <FOOD>={
        9771e842-3e24-4527-aa1d-a4f873972d9f=ok here it is! GIVE <FOOD>
    }
}
