value=food makes you fat, music makes you deaf, art makes you crazy
options=[
    haha alright i guess so
]
options_to_state_uuid_to_attribute_mod={
    haha alright i guess so={
        9f618cec-bc69-45ad-8033-c418767d4b00=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    haha alright i guess so={
        9f618cec-bc69-45ad-8033-c418767d4b00=haha alright i guess so
    }
}
