value=GIVE <FOOD>
options=[
    thanks love
]
options_to_state_uuid_to_attribute_mod={
    thanks love={
        5156ecbb-6d82-43a9-be2c-4061452a48b4=[
            {
                attribute=happiness_mood
                amount=0.1
            }
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    thanks love={
        5156ecbb-6d82-43a9-be2c-4061452a48b4=thanks love
    }
}
