value=good, i hoped you'd say as such
options=[
    FIGHT
    father, what can I do for you?
]
options_to_state_uuid_to_attribute_mod={
    father, what can I do for you?={
        c4067401-b211-4035-a9c7-187ac5f7e3ee=[
        ]
    }
    FIGHT={
        9f794dda-71b8-48e0-b046-05ec700ca829=[
        ]
    }
}
options_to_state_uuid_response={
    father, what can I do for you?={
        c4067401-b211-4035-a9c7-187ac5f7e3ee=father, what can I do for you?
    }
    FIGHT={
        9f794dda-71b8-48e0-b046-05ec700ca829=FIGHT
    }
}
