value=haha no, but i might have got you if you weren't so careful
options=[
    yeah you'll never get me
]
options_to_state_uuid_to_attribute_mod={
    yeah you'll never get me={
        ecbc69c5-ad80-43c4-9876-7d4b0054b342=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    yeah you'll never get me={
        ecbc69c5-ad80-43c4-9876-7d4b0054b342=yeah you'll never get me
    }
}
