value=haha
options=[
    where have you been?
]
options_to_state_uuid_to_attribute_mod={
    where have you been?={
        54270fdf-4738-43da-86f4-b660ab730065=[
            {
                attribute=happiness_mood
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    where have you been?={
        54270fdf-4738-43da-86f4-b660ab730065=where have you been?
    }
}
