value=haha alright i guess so
options=[
    so did you trick anyone today? and I know that's what you do haha
]
options_to_state_uuid_to_attribute_mod={
    so did you trick anyone today? and I know that's what you do haha={
        618cecbc-69c5-4d80-b3c4-18767d4b0054=[
        ]
    }
}
options_to_state_uuid_response={
    so did you trick anyone today? and I know that's what you do haha={
        618cecbc-69c5-4d80-b3c4-18767d4b0054=so did you trick anyone today? and I know that's what you do haha
    }
}
