value=haha, hi <OTHER_NPC_NAME>
options=[
    wait what is your name again?
]
options_to_state_uuid_to_attribute_mod={
    wait what is your name again?={
        38223a2c-8345-4f87-a705-fcbc52a1398f=[
            {
                attribute=anxiety_mood
                amount=-0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    wait what is your name again?={
        38223a2c-8345-4f87-a705-fcbc52a1398f=wait what is your name again?
    }
}
