value=haha, it's not the food <OTHER_NPC_NAME>
options=[
    no? i could have sworn. you sure?
]
options_to_state_uuid_to_attribute_mod={
    no? i could have sworn. you sure?={
        2c854cb5-d623-4bcc-87fa-36682b03ffde=[
        ]
    }
}
options_to_state_uuid_response={
    no? i could have sworn. you sure?={
        2c854cb5-d623-4bcc-87fa-36682b03ffde=no? i could have sworn. you sure?
    }
}
