value=haha no. what've you been doing today?
options=[
    cracking down on wimps
    oh not much, got the better of some guy earlier
]
options_to_state_uuid_to_attribute_mod={
    oh not much, got the better of some guy earlier={
        28c31dc3-a510-4d2e-87ea-f7bd6f9e9325=[
        ]
    }
    cracking down on wimps={
        d6238bcc-c7fa-4668-ab03-ffde1c737ce0=[
        ]
    }
}
options_to_state_uuid_response={
    oh not much, got the better of some guy earlier={
        28c31dc3-a510-4d2e-87ea-f7bd6f9e9325=oh not much, got the better of some guy earlier
    }
    cracking down on wimps={
        d6238bcc-c7fa-4668-ab03-ffde1c737ce0=cracking down on wimps
    }
}
