value=haha good for you, never struck me you'd be into that
options=[
    yeah it's amazing, really amazing
]
options_to_state_uuid_to_attribute_mod={
    yeah it's amazing, really amazing={
        90611552-4899-4d7a-9aac-039df62ba3a7=[
        ]
    }
}
options_to_state_uuid_response={
    yeah it's amazing, really amazing={
        90611552-4899-4d7a-9aac-039df62ba3a7=yeah it's amazing, really amazing
    }
}
