value=have you seen any good stuff for sale today?
options=[
    no i don't think so, what're looking for?
]
options_to_state_uuid_to_attribute_mod={
    no i don't think so, what're looking for?={
        e24fc63f-0104-4deb-9c01-911994b39a89=[
            {
                attribute=anxiety_mood
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    no i don't think so, what're looking for?={
        e24fc63f-0104-4deb-9c01-911994b39a89=no i don't think so, what're looking for?
    }
}
