value=he said he'd help us with <POLITICAL_GOAL>
options=[
    oh great! maybe we should invite him to lunch or something
]
options_to_state_uuid_to_attribute_mod={
    oh great! maybe we should invite him to lunch or something={
        938a6902-eed9-4741-b736-c6c098d92e25=[
        ]
        cefafa0f-58e8-4cbd-a176-a9a939cb5ca2=[
        ]
    }
}
options_to_state_uuid_response={
    oh great! maybe we should invite him to lunch or something={
        938a6902-eed9-4741-b736-c6c098d92e25=oh great! maybe we should invite him to lunch or something
        cefafa0f-58e8-4cbd-a176-a9a939cb5ca2=oh great! maybe we should invite him to lunch or something
    }
}
