value=hello <OTHER_NPC_NAME>!
options=[
    oh hello <OTHER_NPC_NAME>. how goes it?
]
options_to_state_uuid_to_attribute_mod={
    oh hello <OTHER_NPC_NAME>. how goes it?={
        dbfd6ce4-9061-4552-8899-8d7a1aac039d=[
        ]
    }
}
options_to_state_uuid_response={
    oh hello <OTHER_NPC_NAME>. how goes it?={
        dbfd6ce4-9061-4552-8899-8d7a1aac039d=oh hello <OTHER_NPC_NAME>. how goes it?
    }
}
