value=hello
options=[
    how do you do?
    hey dad, what're you doing here today?
]
options_to_state_uuid_to_attribute_mod={
    hey dad, what're you doing here today?={
        3c86d91f-4cfe-4c37-946a-df830555ff9e=[
        ]
    }
    how do you do?={
        e44fbfb6-5bcc-4a05-ac07-feb84198655f=[
        ]
    }
}
options_to_state_uuid_response={
    hey dad, what're you doing here today?={
        3c86d91f-4cfe-4c37-946a-df830555ff9e=hey dad, what're you doing here today?
    }
    how do you do?={
        e44fbfb6-5bcc-4a05-ac07-feb84198655f=how do you do?
    }
}
