value=hello handsome!
options=[
    haha
    haha, hi <OTHER_NPC_NAME>
]
options_to_state_uuid_to_attribute_mod={
    haha, hi <OTHER_NPC_NAME>={
        8e38223a-2c83-459f-87a7-05fcbc52a139=[
        ]
    }
    haha={
        7754270f-df47-4873-9a46-f4b660ab7300=[
            {
                attribute=anxiety_mood
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    haha, hi <OTHER_NPC_NAME>={
        8e38223a-2c83-459f-87a7-05fcbc52a139=haha, hi <OTHER_NPC_NAME>
    }
    haha={
        7754270f-df47-4873-9a46-f4b660ab7300=haha
    }
}
