value=here have this GIVE <FOOD>
options=[
    yummy, bye <OTHER_NPC_NAME>
]
options_to_state_uuid_to_attribute_mod={
    yummy, bye <OTHER_NPC_NAME>={
        9f74b624-2780-456a-832a-f8e8e763bb4a=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    yummy, bye <OTHER_NPC_NAME>={
        9f74b624-2780-456a-832a-f8e8e763bb4a=yummy, bye <OTHER_NPC_NAME>
    }
}
