value=hey why don't we go shoot off some guns
options=[
    how about some explosives too
]
options_to_state_uuid_to_attribute_mod={
    how about some explosives too={
        2c6742b3-cd0d-4963-8d2c-645b2836fc8f=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    how about some explosives too={
        2c6742b3-cd0d-4963-8d2c-645b2836fc8f=how about some explosives too
    }
}
