value=hey were is the <FOOD>
options=[
    oh i don't know
]
options_to_state_uuid_to_attribute_mod={
    oh i don't know={
        6c984e6c-6938-4d10-9dfb-c00c7854074c=[
            {
                attribute=anxiety_mood
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    oh i don't know={
        6c984e6c-6938-4d10-9dfb-c00c7854074c=oh i don't know
    }
}
