value=hey no hitting little one
options=[
    FIGHT
    hi <OTHER_NPC_NAME>
]
options_to_state_uuid_to_attribute_mod={
    hi <OTHER_NPC_NAME>={
        b8b789a7-f8e0-4a90-b5dc-33dfccefa8e5=[
            {
                attribute=friendship
                amount=0.2
            }
        ]
    }
    FIGHT={
        4dda71b8-a8e0-4046-85ec-700ca8290691=[
        ]
    }
}
options_to_state_uuid_response={
    hi <OTHER_NPC_NAME>={
        b8b789a7-f8e0-4a90-b5dc-33dfccefa8e5=hi <OTHER_NPC_NAME>
    }
    FIGHT={
        4dda71b8-a8e0-4046-85ec-700ca8290691=FIGHT
    }
}
