value=hey dad, what're you doing here today?
options=[
    oh just came to see you, was wondering if you wanted to hit the <FUN_PLACE>
]
options_to_state_uuid_to_attribute_mod={
    oh just came to see you, was wondering if you wanted to hit the <FUN_PLACE>={
        86d91f4c-fe0c-4794-aadf-830555ff9e95=[
        ]
    }
}
options_to_state_uuid_response={
    oh just came to see you, was wondering if you wanted to hit the <FUN_PLACE>={
        86d91f4c-fe0c-4794-aadf-830555ff9e95=oh just came to see you, was wondering if you wanted to hit the <FUN_PLACE>
    }
}
