value=hey could you introduce me to one of your high up friends?
options=[
    oh no i don't think so mom, that could ruin things for me
]
options_to_state_uuid_to_attribute_mod={
    oh no i don't think so mom, that could ruin things for me={
        690a03ca-5a8f-4b57-9385-70c77e60f30c=[
            {
                attribute=trust
                amount=-0.2
            }
        ]
    }
}
options_to_state_uuid_response={
    oh no i don't think so mom, that could ruin things for me={
        690a03ca-5a8f-4b57-9385-70c77e60f30c=oh no i don't think so mom, that could ruin things for me
    }
}
