value=hey let's go talk to <WORK_CONTACT>. We'll need their help
options=[
    yeah sure sounds good. who are they again?
]
options_to_state_uuid_to_attribute_mod={
    yeah sure sounds good. who are they again?={
        18fca82c-605c-4ecd-94dd-4fd0c22b4ab3=[
        ]
    }
}
options_to_state_uuid_response={
    yeah sure sounds good. who are they again?={
        18fca82c-605c-4ecd-94dd-4fd0c22b4ab3=yeah sure sounds good. who are they again?
    }
}
