value=hey! haha
options=[
    have you seen any good stuff for sale today?
]
options_to_state_uuid_to_attribute_mod={
    have you seen any good stuff for sale today?={
        9be24fc6-3f01-448d-abdc-01911994b39a=[
            {
                attribute=friendship
                amount=0.4
            }
        ]
    }
}
options_to_state_uuid_response={
    have you seen any good stuff for sale today?={
        9be24fc6-3f01-448d-abdc-01911994b39a=have you seen any good stuff for sale today?
    }
}
