value=hey, how about taking a lady for a stroll?
options=[
    really <OTHER_NPC_NAME>? that'd be great!
]
options_to_state_uuid_to_attribute_mod={
    really <OTHER_NPC_NAME>? that'd be great!={
        87808ddc-370f-475b-87be-947e5bd7d54f=[
            {
                attribute=romance
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    really <OTHER_NPC_NAME>? that'd be great!={
        87808ddc-370f-475b-87be-947e5bd7d54f=really <OTHER_NPC_NAME>? that'd be great!
    }
}
