value=hi <OTHER_NPC_NAME>
options=[
    oh hello! you look rather dashing today <OTHER_NPC_NAME>
]
options_to_state_uuid_to_attribute_mod={
    oh hello! you look rather dashing today <OTHER_NPC_NAME>={
        b789a7f8-e0ca-4075-9c33-dfccefa8e5d4=[
            {
                attribute=romance
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    oh hello! you look rather dashing today <OTHER_NPC_NAME>={
        b789a7f8-e0ca-4075-9c33-dfccefa8e5d4=oh hello! you look rather dashing today <OTHER_NPC_NAME>
    }
}
