value=hi!
options=[
    well heya!
    hi!
    how do you do?
    hello
    hello handsome!
]
options_to_state_uuid_to_attribute_mod={
    hi!={
        921d7dab-86cf-4a66-8250-88c885185355=[
        ]
        93c6b2fb-afa5-486b-a79a-9afb88ef421e=[
        ]
        a57befe6-8319-4f14-b91b-8bc0b007b880=[
            {
                attribute=happiness_mood
                amount=1
            }
        ]
    }
    how do you do?={
        1d7dab86-cf6a-4642-9088-c8851853555f=[
            {
                attribute=friendship
                amount=0.2
            }
        ]
    }
    ={
        7befe683-19df-4479-9b8b-c0b007b880a6=[
        ]
    }
    hello handsome!={
        58775427-0fdf-4738-b3da-46f4b660ab73=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
    hello={
        7de44fbf-b65b-4c5a-85ac-07feb8419865=[
            {
                attribute=happiness_mood
                amount=0.1
            }
        ]
    }
    well heya!={
        f8eb63de-8c6c-467d-a1b0-39084e4e8def=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
        532731b1-6a5d-4934-83be-084ab8bfb43e=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
        f981d993-b91d-4517-9f73-42fb233bcb38=[
            {
                attribute=friendship
                amount=0.1
            }
            {
                attribute=happiness_mood
                amount=0.1
            }
        ]
        9ce83f5e-e614-414b-ab41-9382ff37ed49=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    hi!={
        921d7dab-86cf-4a66-8250-88c885185355=hi!
        93c6b2fb-afa5-486b-a79a-9afb88ef421e=hi!
        a57befe6-8319-4f14-b91b-8bc0b007b880=hi!
    }
    how do you do?={
        1d7dab86-cf6a-4642-9088-c8851853555f=how do you do?
    }
    ={
        7befe683-19df-4479-9b8b-c0b007b880a6=
    }
    hello handsome!={
        58775427-0fdf-4738-b3da-46f4b660ab73=hello handsome!
    }
    hello={
        7de44fbf-b65b-4c5a-85ac-07feb8419865=hello
    }
    well heya!={
        f8eb63de-8c6c-467d-a1b0-39084e4e8def=well heya!
        532731b1-6a5d-4934-83be-084ab8bfb43e=well heya!
        f981d993-b91d-4517-9f73-42fb233bcb38=well heya!
        9ce83f5e-e614-414b-ab41-9382ff37ed49=well heya!
    }
}
