value=hmm, i guess i could do that. i'm rather handy
options=[
    yeah maybe we could make some money selling <INVENTORY_ITEM>
]
options_to_state_uuid_to_attribute_mod={
    yeah maybe we could make some money selling <INVENTORY_ITEM>={
        d12c7ce3-8a5f-4463-a4c1-c14ef3e8f440=[
        ]
    }
}
options_to_state_uuid_response={
    yeah maybe we could make some money selling <INVENTORY_ITEM>={
        d12c7ce3-8a5f-4463-a4c1-c14ef3e8f440=yeah maybe we could make some money selling <INVENTORY_ITEM>
    }
}
