value=how do you fare <OTHER_NPC_NAME>?
options=[
    fair enough for my own needs. though hungry
]
options_to_state_uuid_to_attribute_mod={
    fair enough for my own needs. though hungry={
        1bdd9f74-b624-4780-856a-c32af8e8e763=[
            {
                attribute=trust
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    fair enough for my own needs. though hungry={
        1bdd9f74-b624-4780-856a-c32af8e8e763=fair enough for my own needs. though hungry
    }
}
