value=how about making me some food?
options=[
    oh ok i guess
    huh?
]
options_to_state_uuid_to_attribute_mod={
    huh?={
        4d676d98-67a7-4efa-ba0f-58e87cbd6176=[
        ]
    }
    oh ok i guess={
        7401b211-4035-49c7-987a-c5f7e3ee6749=[
        ]
    }
}
options_to_state_uuid_response={
    huh?={
        4d676d98-67a7-4efa-ba0f-58e87cbd6176=huh?
    }
    oh ok i guess={
        7401b211-4035-49c7-987a-c5f7e3ee6749=oh ok i guess
    }
}
