value=how about you deliver this to <ENEMY_WORK_CONTACT> GIVE <BOMB>
options=[
    uh ok what is it?
]
options_to_state_uuid_to_attribute_mod={
    uh ok what is it?={
        dd0dd1f1-e0d6-4b29-9630-67441e034b16=[
            {
                attribute=anxiety_mood
                amount=1
            }
        ]
    }
}
options_to_state_uuid_response={
    uh ok what is it?={
        dd0dd1f1-e0d6-4b29-9630-67441e034b16=uh ok what is it?
    }
}
