value=how do you do?
options=[
    not well i'm afraid
    out of my way
]
options_to_state_uuid_to_attribute_mod={
    out of my way={
        e59a7538-3722-42b1-92c8-9c5efc7871cb=[
            {
                attribute=anger_mood
                amount=0.1
            }
        ]
    }
    not well i'm afraid={
        4fbfb65b-cc5a-45ac-87fe-b84198655f4b=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    out of my way={
        e59a7538-3722-42b1-92c8-9c5efc7871cb=out of my way
    }
    not well i'm afraid={
        4fbfb65b-cc5a-45ac-87fe-b84198655f4b=not well i'm afraid
    }
}
