value=HUG
options=[
    hey let's go talk to <WORK_CONTACT>. We'll need their help
]
options_to_state_uuid_to_attribute_mod={
    hey let's go talk to <WORK_CONTACT>. We'll need their help={
        4818fca8-2c60-4c7e-8d14-dd4fd0c22b4a=[
        ]
    }
}
options_to_state_uuid_response={
    hey let's go talk to <WORK_CONTACT>. We'll need their help={
        4818fca8-2c60-4c7e-8d14-dd4fd0c22b4a=hey let's go talk to <WORK_CONTACT>. We'll need their help
    }
}
