value=huh?
options=[
    oh sorry, i didn't wasn't talking to you just then
]
options_to_state_uuid_to_attribute_mod={
    oh sorry, i didn't wasn't talking to you just then={
        676d9867-a7ce-4afa-8f58-e87cbd6176a9=[
            {
                attribute=anxiety_mood
                amount=1
            }
        ]
    }
}
options_to_state_uuid_response={
    oh sorry, i didn't wasn't talking to you just then={
        676d9867-a7ce-4afa-8f58-e87cbd6176a9=oh sorry, i didn't wasn't talking to you just then
    }
}
