value=i actually don't feel sad
options=[
    why do you feel mad?
]
options_to_state_uuid_to_attribute_mod={
    why do you feel mad?={
        25478a5b-e042-4092-b381-4b33e10a6a14=[
            {
                attribute=anger_mood
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    why do you feel mad?={
        25478a5b-e042-4092-b381-4b33e10a6a14=why do you feel mad?
    }
}
