value=i always hoped I could find a girl like you
options=[
    hey, how about taking a lady for a stroll?
]
options_to_state_uuid_to_attribute_mod={
    hey, how about taking a lady for a stroll?={
        9687808d-dc37-4fa7-9b07-be947e5bd7d5=[
            {
                attribute=romance
                amount=1
            }
        ]
    }
}
options_to_state_uuid_response={
    hey, how about taking a lady for a stroll?={
        9687808d-dc37-4fa7-9b07-be947e5bd7d5=hey, how about taking a lady for a stroll?
    }
}
