value=i don't have time
options=[
    what about with a beautiful old woman?
]
options_to_state_uuid_to_attribute_mod={
    what about with a beautiful old woman?={
        cc5a05ac-07fe-4841-9865-5f4bbcf4310c=[
            {
                attribute=friendship
                amount=-1
            }
        ]
    }
}
options_to_state_uuid_response={
    what about with a beautiful old woman?={
        cc5a05ac-07fe-4841-9865-5f4bbcf4310c=what about with a beautiful old woman?
    }
}
