value=i don't think so, did you?
options=[
    no, at least I don't think so, ack!
]
options_to_state_uuid_to_attribute_mod={
    no, at least I don't think so, ack!={
        6c6938ad-105d-4bc0-8c78-54074cf23c00=[
            {
                attribute=trust
                amount=-0.2
            }
            {
                attribute=anger_mood
                amount=0.4
            }
        ]
    }
}
options_to_state_uuid_response={
    no, at least I don't think so, ack!={
        6c6938ad-105d-4bc0-8c78-54074cf23c00=no, at least I don't think so, ack!
    }
}
