value=i don't know, just happens
options=[
    well why don't we pass some time walking round
]
options_to_state_uuid_to_attribute_mod={
    well why don't we pass some time walking round={
        7be0376f-48d9-4421-8e1c-f6991e394dfb=[
            {
                attribute=happiness_mood
                amount=-0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    well why don't we pass some time walking round={
        7be0376f-48d9-4421-8e1c-f6991e394dfb=well why don't we pass some time walking round
    }
}
