value=i don't trust you haha
options=[
    ah man ok, well at least tell me something funny
]
options_to_state_uuid_to_attribute_mod={
    ah man ok, well at least tell me something funny={
        e0c47ab9-9f61-4cec-bc69-c5ad8033c418=[
        ]
    }
}
options_to_state_uuid_response={
    ah man ok, well at least tell me something funny={
        e0c47ab9-9f61-4cec-bc69-c5ad8033c418=ah man ok, well at least tell me something funny
    }
}
