value=i love you HUG
options=[
    oh I love you too KISS HUG
]
options_to_state_uuid_to_attribute_mod={
    oh I love you too KISS HUG={
        8f436aa0-ee73-402b-8dae-3498f7e8596c=[
            {
                attribute=romance
                amount=0.3
            }
            {
                attribute=anger_mood
                amount=-1
            }
            {
                attribute=happiness_mood
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    oh I love you too KISS HUG={
        8f436aa0-ee73-402b-8dae-3498f7e8596c=oh I love you too KISS HUG
    }
}
