value=i love you KISS
options=[
    KISS HUG
    wo hey!
]
options_to_state_uuid_to_attribute_mod={
    wo hey!={
        98dfc516-b800-4679-ae9e-c5ec33b2e3ca=[
            {
                attribute=anger_mood
                amount=1
            }
            {
                attribute=trust
                amount=-0.4
            }
        ]
    }
    KISS HUG={
        e0e36c98-4e6c-4938-ad10-5dfbc00c7854=[
            {
                attribute=trust
                amount=0.3
            }
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    wo hey!={
        98dfc516-b800-4679-ae9e-c5ec33b2e3ca=wo hey!
    }
    KISS HUG={
        e0e36c98-4e6c-4938-ad10-5dfbc00c7854=KISS HUG
    }
}
