value=i'm pretending!
options=[
    oh ok, are you a grandma?
]
options_to_state_uuid_to_attribute_mod={
    oh ok, are you a grandma?={
        cbfc4b8f-5a8f-4b7d-a320-0da8b9f00a28=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    oh ok, are you a grandma?={
        cbfc4b8f-5a8f-4b7d-a320-0da8b9f00a28=oh ok, are you a grandma?
    }
}
