value=i'm dying haha
options=[
    wait what!
    oh, yay!
]
options_to_state_uuid_to_attribute_mod={
    oh, yay!={
        c0228684-affb-4587-afb0-96d2df513dec=[
        ]
    }
    wait what!={
        ab86cf6a-6642-4088-8885-1853555fadba=[
            {
                attribute=anxiety_mood
                amount=0.1
            }
        ]
        ec6193f7-0ea4-4b18-a529-a35f6a7a6bbb=[
        ]
    }
}
options_to_state_uuid_response={
    oh, yay!={
        c0228684-affb-4587-afb0-96d2df513dec=oh, yay!
    }
    wait what!={
        ab86cf6a-6642-4088-8885-1853555fadba=wait what!
        ec6193f7-0ea4-4b18-a529-a35f6a7a6bbb=wait what!
    }
}
