value=I've felt sad lately, it's terrible
options=[
    why do you feel sad?
    oh me too, it's in the food!
]
options_to_state_uuid_to_attribute_mod={
    oh me too, it's in the food!={
        665d2c85-4cb5-4623-8bcc-c7fa36682b03=[
        ]
    }
    why do you feel sad?={
        8a657be0-376f-48d9-b421-0e1cf6991e39=[
        ]
    }
}
options_to_state_uuid_response={
    oh me too, it's in the food!={
        665d2c85-4cb5-4623-8bcc-c7fa36682b03=oh me too, it's in the food!
    }
    why do you feel sad?={
        8a657be0-376f-48d9-b421-0e1cf6991e39=why do you feel sad?
    }
}
