value=in what way?
options=[
    i told them about the food!
    what?
    you wouldn't understand haha
]
options_to_state_uuid_to_attribute_mod={
    what?={
        8c74a4c6-9d55-49b4-bbb7-293574e4d1da=[
        ]
    }
    you wouldn't understand haha={
        342e7d69-4b37-4935-8635-535e6a5abfa4=[
        ]
    }
    i told them about the food!={
        c7fa3668-2b03-4fde-9c73-7ce064ee5518=[
        ]
    }
}
options_to_state_uuid_response={
    what?={
        8c74a4c6-9d55-49b4-bbb7-293574e4d1da=what?
    }
    you wouldn't understand haha={
        342e7d69-4b37-4935-8635-535e6a5abfa4=you wouldn't understand haha
    }
    i told them about the food!={
        c7fa3668-2b03-4fde-9c73-7ce064ee5518=i told them about the food!
    }
}
