value=it's the food isn't it!
options=[
    haha no. what've you been doing today?
    no the foods been great
]
options_to_state_uuid_to_attribute_mod={
    no the foods been great={
        da81d448-18fc-482c-a05c-7ecd14dd4fd0=[
        ]
    }
    haha no. what've you been doing today?={
        b5d6238b-ccc7-4a36-a82b-03ffde1c737c=[
        ]
    }
}
options_to_state_uuid_response={
    no the foods been great={
        da81d448-18fc-482c-a05c-7ecd14dd4fd0=no the foods been great
    }
    haha no. what've you been doing today?={
        b5d6238b-ccc7-4a36-a82b-03ffde1c737c=haha no. what've you been doing today?
    }
}
