value=just a present for them
options=[
    oh ok i'll do that GO_TO <ENEMY_WORK_CONTACT> GIVE <BOMB>
]
options_to_state_uuid_to_attribute_mod={
    oh ok i'll do that GO_TO <ENEMY_WORK_CONTACT> GIVE <BOMB>={
        d1f1e0d6-0b29-4630-a744-1e034b161ef7=[
            {
                attribute=anxiety_mood
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    oh ok i'll do that GO_TO <ENEMY_WORK_CONTACT> GIVE <BOMB>={
        d1f1e0d6-0b29-4630-a744-1e034b161ef7=oh ok i'll do that GO_TO <ENEMY_WORK_CONTACT> GIVE <BOMB>
    }
}
