value=just play or talk. you know, goof off
options=[
    oh ok, well i guess that's alright
]
options_to_state_uuid_to_attribute_mod={
    oh ok, well i guess that's alright={
        e41069b8-f068-4d86-9108-6e3696ef59f4=[
        ]
    }
}
options_to_state_uuid_response={
    oh ok, well i guess that's alright={
        e41069b8-f068-4d86-9108-6e3696ef59f4=oh ok, well i guess that's alright
    }
}
