value=just take a break and come with me
options=[
    oh ok, i think i need a break
]
options_to_state_uuid_to_attribute_mod={
    oh ok, i think i need a break={
        4cfe0c37-946a-4f83-8555-ff9e9525ccfd=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    oh ok, i think i need a break={
        4cfe0c37-946a-4f83-8555-ff9e9525ccfd=oh ok, i think i need a break
    }
}
