value=KISS, KISS
options=[
    shall we go for a walk?
]
options_to_state_uuid_to_attribute_mod={
    shall we go for a walk?={
        3b18a529-a35f-4a7a-abbb-fcde0a3a487b=[
            {
                attribute=romance
                amount=0.1
            }
            {
                attribute=trust
                amount=-0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    shall we go for a walk?={
        3b18a529-a35f-4a7a-abbb-fcde0a3a487b=shall we go for a walk?
    }
}
