value=look who's talking
options=[
    oh sorry, i don't know why i said that
    hey anyway, can you go get me some food, i'm hungry
]
options_to_state_uuid_to_attribute_mod={
    hey anyway, can you go get me some food, i'm hungry={
        43b82de0-d496-4174-b05c-a64fc8968b81=[
        ]
    }
    oh sorry, i don't know why i said that={
        943e7608-64eb-41d1-ac7c-e38a5f7463e4=[
        ]
    }
}
options_to_state_uuid_response={
    hey anyway, can you go get me some food, i'm hungry={
        43b82de0-d496-4174-b05c-a64fc8968b81=hey anyway, can you go get me some food, i'm hungry
    }
    oh sorry, i don't know why i said that={
        943e7608-64eb-41d1-ac7c-e38a5f7463e4=oh sorry, i don't know why i said that
    }
}
