value=meh, you know just hanging out
options=[
    oh ok, well nice to see young people like you around
]
options_to_state_uuid_to_attribute_mod={
    oh ok, well nice to see young people like you around={
        3bc3763c-46de-4256-ba56-2140460e6b4c=[
            {
                attribute=anger_mood
                amount=0.3
            }
        ]
    }
}
options_to_state_uuid_response={
    oh ok, well nice to see young people like you around={
        3bc3763c-46de-4256-ba56-2140460e6b4c=oh ok, well nice to see young people like you around
    }
}
