value=nah I forgot haha
options=[
    you'll remember when we get there LEAD
]
options_to_state_uuid_to_attribute_mod={
    you'll remember when we get there LEAD={
        6a786829-87a6-4f2b-8fce-ad4899710833=[
        ]
        2c605c7e-cd14-4d4f-90c2-2b4ab30d3a18=[
        ]
    }
}
options_to_state_uuid_response={
    you'll remember when we get there LEAD={
        6a786829-87a6-4f2b-8fce-ad4899710833=you'll remember when we get there LEAD
        2c605c7e-cd14-4d4f-90c2-2b4ab30d3a18=you'll remember when we get there LEAD
    }
}
