value=no but a cute young man would be nice
options=[
    oh freak! goodbye <OTHER_NPC_NAME>
]
options_to_state_uuid_to_attribute_mod={
    oh freak! goodbye <OTHER_NPC_NAME>={
        432251e7-72f8-4c2a-94d7-4035c641f037=[
        ]
    }
}
options_to_state_uuid_response={
    oh freak! goodbye <OTHER_NPC_NAME>={
        432251e7-72f8-4c2a-94d7-4035c641f037=oh freak! goodbye <OTHER_NPC_NAME>
    }
}
