value=no but maybe I could be with you
options=[
    you will not!
]
options_to_state_uuid_to_attribute_mod={
    you will not!={
        5ae18d98-d479-41d4-bf29-ef19a3fb1860=[
            {
                attribute=friendship
                amount=-2
            }
        ]
    }
}
options_to_state_uuid_response={
    you will not!={
        5ae18d98-d479-41d4-bf29-ef19a3fb1860=you will not!
    }
}
