value=no i've seen much better
options=[
    well there's been a recent sell off, you probably don't want to pass this up
]
options_to_state_uuid_to_attribute_mod={
    well there's been a recent sell off, you probably don't want to pass this up={
        f09592e5-eb97-4236-b2c9-f5412f391d51=[
        ]
    }
}
options_to_state_uuid_response={
    well there's been a recent sell off, you probably don't want to pass this up={
        f09592e5-eb97-4236-b2c9-f5412f391d51=well there's been a recent sell off, you probably don't want to pass this up
    }
}
