value=no, i've enough with that craziness. i'm just a trader!
options=[
    ah come on! it's good!...ish i guess
]
options_to_state_uuid_to_attribute_mod={
    ah come on! it's good!...ish i guess={
        0e7c4b2d-0c12-43f6-b147-72561b7c5a5d=[
        ]
    }
}
options_to_state_uuid_response={
    ah come on! it's good!...ish i guess={
        0e7c4b2d-0c12-43f6-b147-72561b7c5a5d=ah come on! it's good!...ish i guess
    }
}
