value=no? i could have sworn. you sure?
options=[
    aye, though i do feel a little better now
]
options_to_state_uuid_to_attribute_mod={
    aye, though i do feel a little better now={
        854cb5d6-238b-4cc7-ba36-682b03ffde1c=[
        ]
    }
}
options_to_state_uuid_response={
    aye, though i do feel a little better now={
        854cb5d6-238b-4cc7-ba36-682b03ffde1c=aye, though i do feel a little better now
    }
}
