value=nope!
options=[
    why not? it's fun
]
options_to_state_uuid_to_attribute_mod={
    why not? it's fun={
        24a3e0c4-7ab9-4f61-8cec-bc69c5ad8033=[
            {
                attribute=happiness_mood
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    why not? it's fun={
        24a3e0c4-7ab9-4f61-8cec-bc69c5ad8033=why not? it's fun
    }
}
