value=not well i'm afraid
options=[
    what a shame
]
options_to_state_uuid_to_attribute_mod={
    what a shame={
        12d35f59-607c-4afe-97dc-3b5b3003ab82=[
        ]
        bfb65bcc-5a05-4c07-beb8-4198655f4bbc=[
            {
                attribute=happiness_mood
                amount=0.1
            }
        ]
        1cbc8a65-7be0-476f-88d9-34210e1cf699=[
            {
                attribute=happiness_mood
                amount=-0.1
            }
            {
                attribute=trust
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    what a shame={
        12d35f59-607c-4afe-97dc-3b5b3003ab82=what a shame
        bfb65bcc-5a05-4c07-beb8-4198655f4bbc=what a shame
        1cbc8a65-7be0-476f-88d9-34210e1cf699=what a shame
    }
}
