value=oh but i'm so old. i'm just a poop
options=[
    poops can be cool too. come on lets build a ship
]
options_to_state_uuid_to_attribute_mod={
    poops can be cool too. come on lets build a ship={
        7ce38a5f-7463-44c1-814e-f3e8f440e13f=[
        ]
    }
}
options_to_state_uuid_response={
    poops can be cool too. come on lets build a ship={
        7ce38a5f-7463-44c1-814e-f3e8f440e13f=poops can be cool too. come on lets build a ship
    }
}
