value=oh freak! goodbye <OTHER_NPC_NAME>
options=[
    wait why go?
    oh ok, farewell
]
options_to_state_uuid_to_attribute_mod={
    oh ok, farewell={
        b89b173d-0649-4d2e-9c45-26d85188b765=[
        ]
    }
    wait why go?={
        2251e772-f86c-4a54-9740-35c641f0376d=[
            {
                attribute=happiness_mood
                amount=-0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    oh ok, farewell={
        b89b173d-0649-4d2e-9c45-26d85188b765=oh ok, farewell
    }
    wait why go?={
        2251e772-f86c-4a54-9740-35c641f0376d=wait why go?
    }
}
