value=oh great! maybe we should invite him to lunch or something
options=[
    oh yeah good idea, i think that would be good.
    how about we just meet him at <SECRET_CRIME_PLACE>
]
options_to_state_uuid_to_attribute_mod={
    how about we just meet him at <SECRET_CRIME_PLACE>={
        8a6902ee-d977-4177-b6c6-c098d92e25cf=[
        ]
    }
    oh yeah good idea, i think that would be good.={
        fafa0f58-e87c-4d61-b6a9-a939cb5ca289=[
        ]
    }
}
options_to_state_uuid_response={
    how about we just meet him at <SECRET_CRIME_PLACE>={
        8a6902ee-d977-4177-b6c6-c098d92e25cf=how about we just meet him at <SECRET_CRIME_PLACE>
    }
    oh yeah good idea, i think that would be good.={
        fafa0f58-e87c-4d61-b6a9-a939cb5ca289=oh yeah good idea, i think that would be good.
    }
}
