value=oh good, what'd he say
options=[
    he said he'd help us with <POLITICAL_GOAL>
]
options_to_state_uuid_to_attribute_mod={
    he said he'd help us with <POLITICAL_GOAL>={
        a7cefafa-0f58-487c-bd61-76a9a939cb5c=[
            {
                attribute=happiness_mood
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    he said he'd help us with <POLITICAL_GOAL>={
        a7cefafa-0f58-487c-bd61-76a9a939cb5c=he said he'd help us with <POLITICAL_GOAL>
    }
}
