value=oh good, it always pleases me to here that
options=[
    father, why don't you make us a ship sometime
    yeah i know, i always love to see someone trip
]
options_to_state_uuid_to_attribute_mod={
    yeah i know, i always love to see someone trip={
        0d7d3bef-e94d-4c9d-b6d8-3824e3f2e152=[
        ]
    }
    father, why don't you make us a ship sometime={
        eba1d12c-7ce3-4a5f-b463-e4c1c14ef3e8=[
        ]
    }
}
options_to_state_uuid_response={
    yeah i know, i always love to see someone trip={
        0d7d3bef-e94d-4c9d-b6d8-3824e3f2e152=yeah i know, i always love to see someone trip
    }
    father, why don't you make us a ship sometime={
        eba1d12c-7ce3-4a5f-b463-e4c1c14ef3e8=father, why don't you make us a ship sometime
    }
}
