value=oh hey <OTHER_NPC_NAME>
options=[
    what have you been up too?
]
options_to_state_uuid_to_attribute_mod={
    what have you been up too?={
        397a4250-3bc3-463c-86de-52563a562140=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    what have you been up too?={
        397a4250-3bc3-463c-86de-52563a562140=what have you been up too?
    }
}
