value=oh hello! you look rather dashing today <OTHER_NPC_NAME>
options=[
    oh thanks
]
options_to_state_uuid_to_attribute_mod={
    oh thanks={
        89a7f8e0-ca90-45dc-b3df-ccefa8e5d44f=[
            {
                attribute=romance
                amount=-0.4
            }
            {
                attribute=friendship
                amount=-0.3
            }
        ]
    }
}
options_to_state_uuid_response={
    oh thanks={
        89a7f8e0-ca90-45dc-b3df-ccefa8e5d44f=oh thanks
    }
}
