value=oh haha, my bad
options=[
    hey why don't we go shoot off some guns
]
options_to_state_uuid_to_attribute_mod={
    hey why don't we go shoot off some guns={
        762c6742-b3cd-4d29-a3cd-2c645b2836fc=[
            {
                attribute=anxiety_mood
                amount=0.1
            }
        ]
    }
    ={
        6f69a1a3-fe74-436c-a628-ae444a820bb6=[
            {
                attribute=anger_mood
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    hey why don't we go shoot off some guns={
        762c6742-b3cd-4d29-a3cd-2c645b2836fc=hey why don't we go shoot off some guns
    }
    ={
        6f69a1a3-fe74-436c-a628-ae444a820bb6=
    }
}
