value=oh hello <OTHER_NPC_NAME>. how goes it?
options=[
    all good! what you have been up to?
]
options_to_state_uuid_to_attribute_mod={
    all good! what you have been up to?={
        fd6ce490-6115-4248-998d-7a1aac039df6=[
            {
                attribute=happiness_mood
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    all good! what you have been up to?={
        fd6ce490-6115-4248-998d-7a1aac039df6=all good! what you have been up to?
    }
}
