value=oh hey litle one
options=[
    hello old one?
]
options_to_state_uuid_to_attribute_mod={
    hello old one?={
        c6239be2-4fc6-4f01-848d-ebdc01911994=[
            {
                attribute=friendship
                amount=0.1
            }
            {
                attribute=anger_mood
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    hello old one?={
        c6239be2-4fc6-4f01-848d-ebdc01911994=hello old one?
    }
}
