value=oh i've been <RECENT_ACTIVITY>
options=[
    haha good for you, never struck me you'd be into that
]
options_to_state_uuid_to_attribute_mod={
    haha good for you, never struck me you'd be into that={
        e4906115-5248-498d-ba1a-ac039df62ba3=[
        ]
    }
}
options_to_state_uuid_response={
    haha good for you, never struck me you'd be into that={
        e4906115-5248-498d-ba1a-ac039df62ba3=haha good for you, never struck me you'd be into that
    }
}
