value=oh i don't know
options=[
    did you use it recently?
]
options_to_state_uuid_to_attribute_mod={
    did you use it recently?={
        984e6c69-38ad-405d-bbc0-0c7854074cf2=[
            {
                attribute=anger_mood
                amount=0.2
            }
        ]
    }
}
options_to_state_uuid_response={
    did you use it recently?={
        984e6c69-38ad-405d-bbc0-0c7854074cf2=did you use it recently?
    }
}
