value=oh i have to work right now, though that does sound fun
options=[
    just take a break and come with me
]
options_to_state_uuid_to_attribute_mod={
    just take a break and come with me={
        1f4cfe0c-3794-4adf-8305-55ff9e9525cc=[
        ]
    }
}
options_to_state_uuid_response={
    just take a break and come with me={
        1f4cfe0c-3794-4adf-8305-55ff9e9525cc=just take a break and come with me
    }
}
