value=oh just came to see you, was wondering if you wanted to hit the <FUN_PLACE>
options=[
    oh i have to work right now, though that does sound fun
]
options_to_state_uuid_to_attribute_mod={
    oh i have to work right now, though that does sound fun={
        d91f4cfe-0c37-446a-9f83-0555ff9e9525=[
            {
                attribute=friendship
                amount=0.4
            }
        ]
    }
}
options_to_state_uuid_response={
    oh i have to work right now, though that does sound fun={
        d91f4cfe-0c37-446a-9f83-0555ff9e9525=oh i have to work right now, though that does sound fun
    }
}
