value=oh me too, it's in the food!
options=[
    haha, it's not the food <OTHER_NPC_NAME>
]
options_to_state_uuid_to_attribute_mod={
    haha, it's not the food <OTHER_NPC_NAME>={
        5d2c854c-b5d6-438b-8cc7-fa36682b03ff=[
        ]
    }
}
options_to_state_uuid_response={
    haha, it's not the food <OTHER_NPC_NAME>={
        5d2c854c-b5d6-438b-8cc7-fa36682b03ff=haha, it's not the food <OTHER_NPC_NAME>
    }
}
