value=oh nope haha
options=[
    hey <OTHER_NPC_NAME>, come here
]
options_to_state_uuid_to_attribute_mod={
    hey <OTHER_NPC_NAME>, come here={
        c5477b8f-436a-40ee-b340-2bcdae3498f7=[
            {
                attribute=anger_mood
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    hey <OTHER_NPC_NAME>, come here={
        c5477b8f-436a-40ee-b340-2bcdae3498f7=hey <OTHER_NPC_NAME>, come here
    }
}
