value=oh ok, where have you been today?
options=[
    oh just wandering around really, been working some
]
options_to_state_uuid_to_attribute_mod={
    oh just wandering around really, been working some={
        f70ea43b-18a5-49a3-9f6a-7a6bbbfcde0a=[
        ]
    }
}
options_to_state_uuid_response={
    oh just wandering around really, been working some={
        f70ea43b-18a5-49a3-9f6a-7a6bbbfcde0a=oh just wandering around really, been working some
    }
}
