value=oh ok sorry. hey maybe we should go sometime
options=[
    yeah sure, that'd be great! do you want to go now?
]
options_to_state_uuid_to_attribute_mod={
    yeah sure, that'd be great! do you want to go now?={
        da781316-1c18-4116-b100-bac5b11f9101=[
            {
                attribute=friendship
                amount=0.1
            }
            {
                attribute=romance
                amount=0.1
            }
        ]
        48998d7a-1aac-439d-b62b-a3a72174438c=[
            {
                attribute=friendship
                amount=0.2
            }
        ]
    }
}
options_to_state_uuid_response={
    yeah sure, that'd be great! do you want to go now?={
        da781316-1c18-4116-b100-bac5b11f9101=yeah sure, that'd be great! do you want to go now?
        48998d7a-1aac-439d-b62b-a3a72174438c=yeah sure, that'd be great! do you want to go now?
    }
}
