value=oh ok haha. hey how've you been?
options=[
    oh pretty good! i talked to <WORK_CONTACT> recently
]
options_to_state_uuid_to_attribute_mod={
    oh pretty good! i talked to <WORK_CONTACT> recently={
        9867a7ce-fafa-4f58-a87c-bd6176a9a939=[
        ]
    }
}
options_to_state_uuid_response={
    oh pretty good! i talked to <WORK_CONTACT> recently={
        9867a7ce-fafa-4f58-a87c-bd6176a9a939=oh pretty good! i talked to <WORK_CONTACT> recently
    }
}
