value=oh pretty good! i talked to <WORK_CONTACT> recently
options=[
    oh good, what'd he say
]
options_to_state_uuid_to_attribute_mod={
    oh good, what'd he say={
        67a7cefa-fa0f-48e8-bcbd-6176a9a939cb=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    oh good, what'd he say={
        67a7cefa-fa0f-48e8-bcbd-6176a9a939cb=oh good, what'd he say
    }
}
