value=oh poop you weren't who i though you were
options=[
    oh ok, well hands to yourself!
]
options_to_state_uuid_to_attribute_mod={
    oh ok, well hands to yourself!={
        c516b800-b679-4e9e-85ec-33b2e3ca2093=[
            {
                attribute=anger_mood
                amount=-0.5
            }
        ]
    }
}
options_to_state_uuid_response={
    oh ok, well hands to yourself!={
        c516b800-b679-4e9e-85ec-33b2e3ca2093=oh ok, well hands to yourself!
    }
}
