value=oh right, yeah my bad. 
options=[
    HUG
    don't worry about it
]
options_to_state_uuid_to_attribute_mod={
    don't worry about it={
        c8ab690a-03ca-4a8f-9b57-538570c77e60=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
    HUG={
        d44818fc-a82c-405c-becd-14dd4fd0c22b=[
            {
                attribute=anxiety_mood
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    don't worry about it={
        c8ab690a-03ca-4a8f-9b57-538570c77e60=don't worry about it
    }
    HUG={
        d44818fc-a82c-405c-becd-14dd4fd0c22b=HUG
    }
}
