value=oh sorry, i didn't wasn't talking to you just then
options=[
    oh ok haha. hey how've you been?
]
options_to_state_uuid_to_attribute_mod={
    oh ok haha. hey how've you been?={
        6d9867a7-cefa-4a0f-98e8-7cbd6176a9a9=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    oh ok haha. hey how've you been?={
        6d9867a7-cefa-4a0f-98e8-7cbd6176a9a9=oh ok haha. hey how've you been?
    }
}
