value=oh sorry, i don't know why i said that
options=[
    oh ok whatever
]
options_to_state_uuid_to_attribute_mod={
    oh ok whatever={
        3e760864-eba1-412c-bce3-8a5f7463e4c1=[
            {
                attribute=anger_mood
                amount=-0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    oh ok whatever={
        3e760864-eba1-412c-bce3-8a5f7463e4c1=oh ok whatever
    }
}
