value=oh that's right! the handsome man that took me for a stroll last evening
options=[
    haha, uh no, listen I got to go
]
options_to_state_uuid_to_attribute_mod={
    haha, uh no, listen I got to go={
        2c83459f-87a7-45fc-bc52-a1398f79723e=[
            {
                attribute=anxiety_mood
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    haha, uh no, listen I got to go={
        2c83459f-87a7-45fc-bc52-a1398f79723e=haha, uh no, listen I got to go
    }
}
