value=oh thanks <OTHER_NPC_NAME>
options=[
    yeah sure, hey do you want to make something again?
]
options_to_state_uuid_to_attribute_mod={
    yeah sure, hey do you want to make something again?={
        b122d39c-f2ed-42f4-b85b-6400a1ad5151=[
        ]
    }
}
options_to_state_uuid_response={
    yeah sure, hey do you want to make something again?={
        b122d39c-f2ed-42f4-b85b-6400a1ad5151=yeah sure, hey do you want to make something again?
    }
}
