value=oh you know, the usual
options=[
    oh really, what's the usual?
]
options_to_state_uuid_to_attribute_mod={
    oh really, what's the usual?={
        42503bc3-763c-46de-9256-3a562140460e=[
            {
                attribute=friendship
                amount=1
            }
        ]
    }
}
options_to_state_uuid_response={
    oh really, what's the usual?={
        42503bc3-763c-46de-9256-3a562140460e=oh really, what's the usual?
    }
}
