value=oh yeah good idea, i think that would be good.
options=[
    do you think you could do that?
]
options_to_state_uuid_to_attribute_mod={
    do you think you could do that?={
        fa0f58e8-7cbd-4176-a9a9-39cb5ca289fb=[
        ]
    }
}
options_to_state_uuid_response={
    do you think you could do that?={
        fa0f58e8-7cbd-4176-a9a9-39cb5ca289fb=do you think you could do that?
    }
}
