value=oh you know, help understand things
options=[
    in what way?
]
options_to_state_uuid_to_attribute_mod={
    in what way?={
        3c342e7d-694b-4789-b5c6-35535e6a5abf=[
            {
                attribute=anger_mood
                amount=0.1
            }
        ]
        ccc7fa36-682b-43ff-9e1c-737ce064ee55=[
        ]
    }
}
options_to_state_uuid_response={
    in what way?={
        3c342e7d-694b-4789-b5c6-35535e6a5abf=in what way?
        ccc7fa36-682b-43ff-9e1c-737ce064ee55=in what way?
    }
}
