value=oh you old fellow! where have you been all this time
options=[
    you're beautiful <OTHER_NPC_NAME>
]
options_to_state_uuid_to_attribute_mod={
    you're beautiful <OTHER_NPC_NAME>={
        55f22c96-8780-4ddc-b70f-a75b07be947e=[
            {
                attribute=romance
                amount=0.3
            }
        ]
    }
}
options_to_state_uuid_response={
    you're beautiful <OTHER_NPC_NAME>={
        55f22c96-8780-4ddc-b70f-a75b07be947e=you're beautiful <OTHER_NPC_NAME>
    }
}
