value=oh yes I suppose
options=[
    care to join me for stroll?
    i have <INVENTORY_ITEM>, sold at <EVIL_PRICE>. A real bargain
]
options_to_state_uuid_to_attribute_mod={
    i have <INVENTORY_ITEM>, sold at <EVIL_PRICE>. A real bargain={
        c745bef7-f095-42e5-ab97-9236b2c9f541=[
        ]
    }
    care to join me for stroll?={
        7c6f68b2-a111-410f-af6a-6996f58cb5cf=[
        ]
    }
}
options_to_state_uuid_response={
    i have <INVENTORY_ITEM>, sold at <EVIL_PRICE>. A real bargain={
        c745bef7-f095-42e5-ab97-9236b2c9f541=i have <INVENTORY_ITEM>, sold at <EVIL_PRICE>. A real bargain
    }
    care to join me for stroll?={
        7c6f68b2-a111-410f-af6a-6996f58cb5cf=care to join me for stroll?
    }
}
