value=oh you thank you
options=[
    i always hoped I could find a girl like you
]
options_to_state_uuid_to_attribute_mod={
    i always hoped I could find a girl like you={
        2c968780-8ddc-470f-a75b-07be947e5bd7=[
            {
                attribute=anxiety_mood
                amount=0.2
            }
            {
                attribute=romance
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    i always hoped I could find a girl like you={
        2c968780-8ddc-470f-a75b-07be947e5bd7=i always hoped I could find a girl like you
    }
}
