value=oh, i'm doing well. i see you at times here
options=[
    as do i, a fare lady is hard to come by
    yeah i come here with friends sometimes
]
options_to_state_uuid_to_attribute_mod={
    yeah i come here with friends sometimes={
        140fdce4-1069-48f0-a89d-86d1086e3696=[
        ]
    }
    as do i, a fare lady is hard to come by={
        a83a7c6f-68b2-4111-810f-6f6a6996f58c=[
            {
                attribute=romance
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    yeah i come here with friends sometimes={
        140fdce4-1069-48f0-a89d-86d1086e3696=yeah i come here with friends sometimes
    }
    as do i, a fare lady is hard to come by={
        a83a7c6f-68b2-4111-810f-6f6a6996f58c=as do i, a fare lady is hard to come by
    }
}
