value=ok here it is! GIVE <FOOD>
options=[
    oh thanks!
]
options_to_state_uuid_to_attribute_mod={
    oh thanks!={
        71e8423e-2415-47aa-9da4-f873972d9f84=[
            {
                attribute=happiness_mood
                amount=0.1
            }
            {
                attribute=friendship
                amount=1
            }
        ]
    }
}
options_to_state_uuid_response={
    oh thanks!={
        71e8423e-2415-47aa-9da4-f873972d9f84=oh thanks!
    }
}
