value=ok sure
options=[
    ok good
    now i'm the boss ok?
    what was that?
]
options_to_state_uuid_to_attribute_mod={
    what was that?={
        2298c026-190e-4c4b-ad0c-1223f6714772=[
        ]
    }
    now i'm the boss ok?={
        200da8b9-f00a-481c-9132-30aea52399ee=[
            {
                attribute=happiness_mood
                amount=0.1
            }
        ]
    }
    ok good={
        8fbb7de3-200d-48b9-b00a-281c513230ae=[
        ]
    }
}
options_to_state_uuid_response={
    what was that?={
        2298c026-190e-4c4b-ad0c-1223f6714772=what was that?
    }
    now i'm the boss ok?={
        200da8b9-f00a-481c-9132-30aea52399ee=now i'm the boss ok?
    }
    ok good={
        8fbb7de3-200d-48b9-b00a-281c513230ae=ok good
    }
}
