value=old fart! what
options=[
    yeah you old fart
    sorry <OTHER_NPC_NAME>. How do you fare?
    who are you talking about?
]
options_to_state_uuid_to_attribute_mod={
    who are you talking about?={
        162245c5-477b-4f43-aaa0-ee73402bcdae=[
        ]
    }
    sorry <OTHER_NPC_NAME>. How do you fare?={
        d195a83a-7c6f-48b2-a111-810f6f6a6996=[
        ]
    }
    yeah you old fart={
        09f7050d-33b3-44cc-8808-c994173cb3be=[
        ]
    }
}
options_to_state_uuid_response={
    who are you talking about?={
        162245c5-477b-4f43-aaa0-ee73402bcdae=who are you talking about?
    }
    sorry <OTHER_NPC_NAME>. How do you fare?={
        d195a83a-7c6f-48b2-a111-810f6f6a6996=sorry <OTHER_NPC_NAME>. How do you fare?
    }
    yeah you old fart={
        09f7050d-33b3-44cc-8808-c994173cb3be=yeah you old fart
    }
}
