value=only fooling
options=[
    oh good! haha
    oh ok, where have you been today?
]
options_to_state_uuid_to_attribute_mod={
    oh ok, where have you been today?={
        93f70ea4-3b18-4529-a35f-6a7a6bbbfcde=[
        ]
    }
    oh good! haha={
        cf6a6642-5088-4885-9853-555fadba7d6f=[
            {
                attribute=friendship
                amount=0.1
            }
            {
                attribute=anxiety_mood
                amount=-0.4
            }
        ]
    }
}
options_to_state_uuid_response={
    oh ok, where have you been today?={
        93f70ea4-3b18-4529-a35f-6a7a6bbbfcde=oh ok, where have you been today?
    }
    oh good! haha={
        cf6a6642-5088-4885-9853-555fadba7d6f=oh good! haha
    }
}
