value=or you could go get me a <PET_ANIMAL>?
options=[
    haha you want a <PET_ANIMAL> now?
]
options_to_state_uuid_to_attribute_mod={
    haha you want a <PET_ANIMAL> now?={
        e0d49641-74f0-4ca6-8fc8-968b8149a8f1=[
        ]
    }
}
options_to_state_uuid_response={
    haha you want a <PET_ANIMAL> now?={
        e0d49641-74f0-4ca6-8fc8-968b8149a8f1=haha you want a <PET_ANIMAL> now?
    }
}
