value=really <OTHER_NPC_NAME>? that'd be great!
options=[
    alright then HUG LEAD
]
options_to_state_uuid_to_attribute_mod={
    alright then HUG LEAD={
        808ddc37-0fa7-4b07-be94-7e5bd7d54f05=[
            {
                attribute=romance
                amount=0.2
            }
        ]
    }
}
options_to_state_uuid_response={
    alright then HUG LEAD={
        808ddc37-0fa7-4b07-be94-7e5bd7d54f05=alright then HUG LEAD
    }
}
