value=shall we go for a walk?
options=[
    sure, lead on FOLLOW
]
options_to_state_uuid_to_attribute_mod={
    sure, lead on FOLLOW={
        18a529a3-5f6a-4a6b-bbfc-de0a3a487b75=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    sure, lead on FOLLOW={
        18a529a3-5f6a-4a6b-bbfc-de0a3a487b75=sure, lead on FOLLOW
    }
}
