value=so did you trick anyone today? and I know that's what you do haha
options=[
    haha no, but i might have got you if you weren't so careful
]
options_to_state_uuid_to_attribute_mod={
    haha no, but i might have got you if you weren't so careful={
        8cecbc69-c5ad-4033-8418-767d4b0054b3=[
        ]
    }
}
options_to_state_uuid_response={
    haha no, but i might have got you if you weren't so careful={
        8cecbc69-c5ad-4033-8418-767d4b0054b3=haha no, but i might have got you if you weren't so careful
    }
}
