value=so how are things my daughter
options=[
    all's well father
    daughter haha
]
options_to_state_uuid_to_attribute_mod={
    daughter haha={
        c08c55f2-2c96-4780-8ddc-370fa75b07be=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
    all's well father={
        0864eba1-d12c-4ce3-8a5f-7463e4c1c14e=[
        ]
    }
}
options_to_state_uuid_response={
    daughter haha={
        c08c55f2-2c96-4780-8ddc-370fa75b07be=daughter haha
    }
    all's well father={
        0864eba1-d12c-4ce3-8a5f-7463e4c1c14e=all's well father
    }
}
