value=so how do you fare?
options=[
    oh fare enough, i found a new prospect for coins
]
options_to_state_uuid_to_attribute_mod={
    oh fare enough, i found a new prospect for coins={
        050d33b3-64cc-4808-8994-173cb3be6dba=[
            {
                attribute=anger_mood
                amount=-0.2
            }
        ]
    }
}
options_to_state_uuid_response={
    oh fare enough, i found a new prospect for coins={
        050d33b3-64cc-4808-8994-173cb3be6dba=oh fare enough, i found a new prospect for coins
    }
}
