value=so what do you do with your friends?
options=[
    just play or talk. you know, goof off
]
options_to_state_uuid_to_attribute_mod={
    just play or talk. you know, goof off={
        dce41069-b8f0-489d-86d1-086e3696ef59=[
            {
                attribute=anxiety_mood
                amount=-0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    just play or talk. you know, goof off={
        dce41069-b8f0-489d-86d1-086e3696ef59=just play or talk. you know, goof off
    }
}
