value=sorry <OTHER_NPC_NAME>. How do you fare?
options=[
    oh, i'm doing well. i see you at times here
]
options_to_state_uuid_to_attribute_mod={
    oh, i'm doing well. i see you at times here={
        95a83a7c-6f68-42a1-9181-0f6f6a6996f5=[
            {
                attribute=friendship
                amount=0.1
            }
            {
                attribute=romance
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    oh, i'm doing well. i see you at times here={
        95a83a7c-6f68-42a1-9181-0f6f6a6996f5=oh, i'm doing well. i see you at times here
    }
}
