value=sure
options=[
    ok i'll help you!
    GIVE <FOOD> here you go
]
options_to_state_uuid_to_attribute_mod={
    GIVE <FOOD> here you go={
        241527aa-1da4-4873-972d-9f84c3510cfa=[
        ]
    }
    ok i'll help you!={
        fe68a62f-dd0d-41f1-a0d6-0b29d6306744=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    GIVE <FOOD> here you go={
        241527aa-1da4-4873-972d-9f84c3510cfa=GIVE <FOOD> here you go
    }
    ok i'll help you!={
        fe68a62f-dd0d-41f1-a0d6-0b29d6306744=ok i'll help you!
    }
}
