value=thanks love
options=[
    sure thing! see you later, GO_TO <FREQUENTED_PLACE>
]
options_to_state_uuid_to_attribute_mod={
    sure thing! see you later, GO_TO <FREQUENTED_PLACE>={
        56ecbb6d-82f3-49fe-ac40-61452a48b4b2=[
        ]
    }
}
options_to_state_uuid_response={
    sure thing! see you later, GO_TO <FREQUENTED_PLACE>={
        56ecbb6d-82f3-49fe-ac40-61452a48b4b2=sure thing! see you later, GO_TO <FREQUENTED_PLACE>
    }
}
