value=uh ok what is it?
options=[
    just a present for them
]
options_to_state_uuid_to_attribute_mod={
    just a present for them={
        0dd1f1e0-d60b-49d6-b067-441e034b161e=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    just a present for them={
        0dd1f1e0-d60b-49d6-b067-441e034b161e=just a present for them
    }
}
