value=very well thanks. hey i got a new job, you want to join?
options=[
    no, i've enough with that craziness. i'm just a trader!
]
options_to_state_uuid_to_attribute_mod={
    no, i've enough with that craziness. i'm just a trader!={
        190e7c4b-2d0c-4223-b671-4772561b7c5a=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    no, i've enough with that craziness. i'm just a trader!={
        190e7c4b-2d0c-4223-b671-4772561b7c5a=no, i've enough with that craziness. i'm just a trader!
    }
}
