value=very funny <OTHER_NPC_NAME>, are you a mule?
options=[
    haha no you old hag
]
options_to_state_uuid_to_attribute_mod={
    haha no you old hag={
        ea781bdd-9f74-4624-a780-c56ac32af8e8=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    haha no you old hag={
        ea781bdd-9f74-4624-a780-c56ac32af8e8=haha no you old hag
    }
}
