value=wait what!
options=[
    only fooling
]
options_to_state_uuid_to_attribute_mod={
    only fooling={
        6193f70e-a43b-48a5-a9a3-5f6a7a6bbbfc=[
        ]
        86cf6a66-4250-48c8-8518-53555fadba7d=[
            {
                attribute=happiness_mood
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    only fooling={
        6193f70e-a43b-48a5-a9a3-5f6a7a6bbbfc=only fooling
        86cf6a66-4250-48c8-8518-53555fadba7d=only fooling
    }
}
