value=well there's been a recent sell off, you probably don't want to pass this up
options=[
    i'll take my chances
    oh hey
]
options_to_state_uuid_to_attribute_mod={
    oh hey={
        8fbdcb24-a3e0-447a-b99f-618cecbc69c5=[
            {
                attribute=anxiety_mood
                amount=0.1
            }
        ]
    }
    i'll take my chances={
        9592e5eb-9792-46b2-89f5-412f391d51cb=[
        ]
    }
}
options_to_state_uuid_response={
    oh hey={
        8fbdcb24-a3e0-447a-b99f-618cecbc69c5=oh hey
    }
    i'll take my chances={
        9592e5eb-9792-46b2-89f5-412f391d51cb=i'll take my chances
    }
}
