value=well heya!
options=[
    how do you do?
    do you want to play?
]
options_to_state_uuid_to_attribute_mod={
    do you want to play?={
        2731b16a-5d79-4483-be08-4ab8bfb43e08=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
    how do you do?={
        eb63de8c-6cd6-4d21-b039-084e4e8def96=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    do you want to play?={
        2731b16a-5d79-4483-be08-4ab8bfb43e08=do you want to play?
    }
    how do you do?={
        eb63de8c-6cd6-4d21-b039-084e4e8def96=how do you do?
    }
}
