value=what do you mean you old fart?
options=[
    old fart! what
]
options_to_state_uuid_to_attribute_mod={
    old fart! what={
        a8d195a8-3a7c-4f68-b2a1-11810f6f6a69=[
            {
                attribute=anger_mood
                amount=0.1
            }
        ]
        8509f705-0d33-4364-8c88-08c994173cb3=[
            {
                attribute=anger_mood
                amount=0.1
            }
            {
                attribute=happiness_mood
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    old fart! what={
        a8d195a8-3a7c-4f68-b2a1-11810f6f6a69=old fart! what
        8509f705-0d33-4364-8c88-08c994173cb3=old fart! what
    }
}
