value=what? GO_TO <OTHER_NPC_NAME>
options=[
    i love you HUG
]
options_to_state_uuid_to_attribute_mod={
    i love you HUG={
        7b8f436a-a0ee-4340-abcd-ae3498f7e859=[
            {
                attribute=romance
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    i love you HUG={
        7b8f436a-a0ee-4340-abcd-ae3498f7e859=i love you HUG
    }
}
