value=what haha. ok whatever, how do you fair?
options=[
    very well thanks. hey i got a new job, you want to join?
]
options_to_state_uuid_to_attribute_mod={
    very well thanks. hey i got a new job, you want to join?={
        26190e7c-4b2d-4c12-a3f6-714772561b7c=[
        ]
    }
}
options_to_state_uuid_response={
    very well thanks. hey i got a new job, you want to join?={
        26190e7c-4b2d-4c12-a3f6-714772561b7c=very well thanks. hey i got a new job, you want to join?
    }
}
