value=what? haha ok stop it
options=[
    why do you feel like a dad! i don't know haha
]
options_to_state_uuid_to_attribute_mod={
    why do you feel like a dad! i don't know haha={
        e0429092-3381-4b33-a10a-6a1468304155=[
        ]
    }
}
options_to_state_uuid_response={
    why do you feel like a dad! i don't know haha={
        e0429092-3381-4b33-a10a-6a1468304155=why do you feel like a dad! i don't know haha
    }
}
