value=what? you're so dumb sometimes
options=[
    look who's talking
]
options_to_state_uuid_to_attribute_mod={
    look who's talking={
        9c943e76-0864-4ba1-912c-7ce38a5f7463=[
            {
                attribute=anger_mood
                amount=1
            }
        ]
    }
}
options_to_state_uuid_response={
    look who's talking={
        9c943e76-0864-4ba1-912c-7ce38a5f7463=look who's talking
    }
}
