value=what about with a beautiful old woman?
options=[
    get away from me hag
    what? you're so dumb sometimes
    what are you talking about?
    oh do you think i'm beautiful?
]
options_to_state_uuid_to_attribute_mod={
    oh do you think i'm beautiful?={
        e8ff90b1-22d3-4cf2-ade2-f4f85b6400a1=[
            {
                attribute=happiness_mood
                amount=0.3
            }
        ]
    }
    what? you're so dumb sometimes={
        8f462d26-b7a2-4543-b7be-14b32256a23a=[
        ]
    }
    what are you talking about?={
        baaf3508-ef95-4319-bd8f-a8d4c5db5d16=[
        ]
    }
    get away from me hag={
        5a05ac07-feb8-4198-a55f-4bbcf4310c14=[
            {
                attribute=anger_mood
                amount=1
            }
        ]
    }
}
options_to_state_uuid_response={
    oh do you think i'm beautiful?={
        e8ff90b1-22d3-4cf2-ade2-f4f85b6400a1=oh do you think i'm beautiful?
    }
    what? you're so dumb sometimes={
        8f462d26-b7a2-4543-b7be-14b32256a23a=what? you're so dumb sometimes
    }
    what are you talking about?={
        baaf3508-ef95-4319-bd8f-a8d4c5db5d16=what are you talking about?
    }
    get away from me hag={
        5a05ac07-feb8-4198-a55f-4bbcf4310c14=get away from me hag
    }
}
