value=what a shame
options=[
    care to pass some time with an old woman?
    I've felt sad lately, it's terrible
    farewell
]
options_to_state_uuid_to_attribute_mod={
    farewell={
        d35f5960-7c0a-4ed7-9c3b-5b3003ab82c5=[
        ]
    }
    I've felt sad lately, it's terrible={
        bc8a657b-e037-4f48-9934-210e1cf6991e=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
    care to pass some time with an old woman?={
        b65bcc5a-05ac-47fe-b841-98655f4bbcf4=[
        ]
    }
}
options_to_state_uuid_response={
    farewell={
        d35f5960-7c0a-4ed7-9c3b-5b3003ab82c5=farewell
    }
    I've felt sad lately, it's terrible={
        bc8a657b-e037-4f48-9934-210e1cf6991e=I've felt sad lately, it's terrible
    }
    care to pass some time with an old woman?={
        b65bcc5a-05ac-47fe-b841-98655f4bbcf4=care to pass some time with an old woman?
    }
}
