value=why not? it's fun
options=[
    i don't trust you haha
    i'm an old turd
]
options_to_state_uuid_to_attribute_mod={
    i'm an old turd={
        f9e027cd-cede-4d95-bc53-fce2eb647e0f=[
        ]
    }
    i don't trust you haha={
        a3e0c47a-b99f-418c-acbc-69c5ad8033c4=[
        ]
    }
}
options_to_state_uuid_response={
    i'm an old turd={
        f9e027cd-cede-4d95-bc53-fce2eb647e0f=i'm an old turd
    }
    i don't trust you haha={
        a3e0c47a-b99f-418c-acbc-69c5ad8033c4=i don't trust you haha
    }
}
