value=why do you feel sad?
options=[
    i don't know, just happens
    i actually don't feel sad
]
options_to_state_uuid_to_attribute_mod={
    i actually don't feel sad={
        2425478a-5be0-4290-9233-814b33e10a6a=[
        ]
    }
    i don't know, just happens={
        657be037-6f48-4934-a10e-1cf6991e394d=[
        ]
    }
}
options_to_state_uuid_response={
    i actually don't feel sad={
        2425478a-5be0-4290-9233-814b33e10a6a=i actually don't feel sad
    }
    i don't know, just happens={
        657be037-6f48-4934-a10e-1cf6991e394d=i don't know, just happens
    }
}
