value=why you?
options=[
    what do you mean you old fart?
]
options_to_state_uuid_to_attribute_mod={
    what do you mean you old fart?={
        d08509f7-050d-43b3-a4cc-8808c994173c=[
            {
                attribute=anger_mood
                amount=0.2
            }
        ]
    }
}
options_to_state_uuid_response={
    what do you mean you old fart?={
        d08509f7-050d-43b3-a4cc-8808c994173c=what do you mean you old fart?
    }
}
