value=wo hey!
options=[
    oh poop you weren't who i though you were
]
options_to_state_uuid_to_attribute_mod={
    oh poop you weren't who i though you were={
        dfc516b8-00b6-496e-9ec5-ec33b2e3ca20=[
            {
                attribute=anxiety_mood
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    oh poop you weren't who i though you were={
        dfc516b8-00b6-496e-9ec5-ec33b2e3ca20=oh poop you weren't who i though you were
    }
}
