value=yeah sure sounds good. who are they again?
options=[
    you don't remember?
    hello <OTHER_NPC_NAME>!
]
options_to_state_uuid_to_attribute_mod={
    hello <OTHER_NPC_NAME>!={
        fedbfd6c-e490-4115-9248-998d7a1aac03=[
        ]
    }
    you don't remember?={
        fca82c60-5c7e-4d14-9d4f-d0c22b4ab30d=[
        ]
    }
}
options_to_state_uuid_response={
    hello <OTHER_NPC_NAME>!={
        fedbfd6c-e490-4115-9248-998d7a1aac03=hello <OTHER_NPC_NAME>!
    }
    you don't remember?={
        fca82c60-5c7e-4d14-9d4f-d0c22b4ab30d=you don't remember?
    }
}
