value=yeah, don't laugh
options=[
    oh ok sorry. hey maybe we should go sometime
]
options_to_state_uuid_to_attribute_mod={
    oh ok sorry. hey maybe we should go sometime={
        5248998d-7a1a-4c03-9df6-2ba3a7217443=[
        ]
    }
}
options_to_state_uuid_response={
    oh ok sorry. hey maybe we should go sometime={
        5248998d-7a1a-4c03-9df6-2ba3a7217443=oh ok sorry. hey maybe we should go sometime
    }
}
