value=yeah maybe we could make some money selling <INVENTORY_ITEM>
options=[
    oh but i'm so old. i'm just a poop
]
options_to_state_uuid_to_attribute_mod={
    oh but i'm so old. i'm just a poop={
        2c7ce38a-5f74-43e4-81c1-4ef3e8f440e1=[
        ]
    }
}
options_to_state_uuid_response={
    oh but i'm so old. i'm just a poop={
        2c7ce38a-5f74-43e4-81c1-4ef3e8f440e1=oh but i'm so old. i'm just a poop
    }
}
