value=yeah sure, hey do you want to make something again?
options=[
    oh ok, I'm a little tired but sure we can do that. MAKE <ART>
]
options_to_state_uuid_to_attribute_mod={
    oh ok, I'm a little tired but sure we can do that. MAKE <ART>={
        22d39cf2-ede2-44f8-9b64-00a1ad5151f6=[
        ]
    }
}
options_to_state_uuid_response={
    oh ok, I'm a little tired but sure we can do that. MAKE <ART>={
        22d39cf2-ede2-44f8-9b64-00a1ad5151f6=oh ok, I'm a little tired but sure we can do that. MAKE <ART>
    }
}
