value=yeah! they're cute
options=[
    why don't we just go see if we can find some outside?
    what are?
]
options_to_state_uuid_to_attribute_mod={
    what are?={
        377e1ab7-eef4-4ed6-a1b4-f89cba1b38d2=[
        ]
    }
    why don't we just go see if we can find some outside?={
        964174f0-5ca6-4fc8-968b-8149a8f13dd9=[
        ]
    }
}
options_to_state_uuid_response={
    what are?={
        377e1ab7-eef4-4ed6-a1b4-f89cba1b38d2=what are?
    }
    why don't we just go see if we can find some outside?={
        964174f0-5ca6-4fc8-968b-8149a8f13dd9=why don't we just go see if we can find some outside?
    }
}
