value=yeah sure, that'd be great! do you want to go now?
options=[
    what? no
    oh sure! i'd love too
]
options_to_state_uuid_to_attribute_mod={
    oh sure! i'd love too={
        7813161c-18c1-4631-80ba-c5b11f910131=[
        ]
    }
    what? no={
        998d7a1a-ac03-4df6-aba3-a72174438c1a=[
        ]
    }
}
options_to_state_uuid_response={
    oh sure! i'd love too={
        7813161c-18c1-4631-80ba-c5b11f910131=oh sure! i'd love too
    }
    what? no={
        998d7a1a-ac03-4df6-aba3-a72174438c1a=what? no
    }
}
