value=yeah no problem!
options=[
    EAT <FOOD> you want some?
]
options_to_state_uuid_to_attribute_mod={
    EAT <FOOD> you want some?={
        423e2415-27aa-4da4-b873-972d9f84c351=[
            {
                attribute=friendship
                amount=0.3
            }
        ]
    }
}
options_to_state_uuid_response={
    EAT <FOOD> you want some?={
        423e2415-27aa-4da4-b873-972d9f84c351=EAT <FOOD> you want some?
    }
}
