value=yeah i come here with friends sometimes
options=[
    so what do you do with your friends?
]
options_to_state_uuid_to_attribute_mod={
    so what do you do with your friends?={
        0fdce410-69b8-4068-9d86-d1086e3696ef=[
            {
                attribute=trust
                amount=-0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    so what do you do with your friends?={
        0fdce410-69b8-4068-9d86-d1086e3696ef=so what do you do with your friends?
    }
}
