value=you will not!
options=[
    and why not!
]
options_to_state_uuid_to_attribute_mod={
    and why not!={
        e18d98d4-7951-443f-a9ef-19a3fb186065=[
            {
                attribute=romance
                amount=1
            }
            {
                attribute=anger_mood
                amount=1
            }
        ]
    }
}
options_to_state_uuid_response={
    and why not!={
        e18d98d4-7951-443f-a9ef-19a3fb186065=and why not!
    }
}
