value=you're a grandpa?
options=[
    no but maybe I could be with you
    very funny <OTHER_NPC_NAME>, are you a mule?
]
options_to_state_uuid_to_attribute_mod={
    very funny <OTHER_NPC_NAME>, are you a mule?={
        e0ea781b-dd9f-44b6-a427-80c56ac32af8=[
            {
                attribute=happiness_mood
                amount=0.1
            }
        ]
    }
    no but maybe I could be with you={
        ae5ae18d-98d4-4951-943f-29ef19a3fb18=[
        ]
    }
}
options_to_state_uuid_response={
    very funny <OTHER_NPC_NAME>, are you a mule?={
        e0ea781b-dd9f-44b6-a427-80c56ac32af8=very funny <OTHER_NPC_NAME>, are you a mule?
    }
    no but maybe I could be with you={
        ae5ae18d-98d4-4951-943f-29ef19a3fb18=no but maybe I could be with you
    }
}
