value=you'll remember when we get there LEAD
options=[
    ok sounds fun
]
options_to_state_uuid_to_attribute_mod={
    ok sounds fun={
        78682987-a67f-4b4f-8ead-4899710833ff=[
            {
                attribute=friendship
                amount=0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    ok sounds fun={
        78682987-a67f-4b4f-8ead-4899710833ff=ok sounds fun
    }
}
