value=yummy, bye <OTHER_NPC_NAME>
options=[
    farwell <OTHER_NPC_NAME>
]
options_to_state_uuid_to_attribute_mod={
    farwell <OTHER_NPC_NAME>={
        74b62427-80c5-4ac3-aaf8-e8e763bb4ac5=[
            {
                attribute=friendship
                amount=-0.1
            }
        ]
    }
}
options_to_state_uuid_response={
    farwell <OTHER_NPC_NAME>={
        74b62427-80c5-4ac3-aaf8-e8e763bb4ac5=farwell <OTHER_NPC_NAME>
    }
}
