uuid=01b21140-35e9-4718-bac5-f7e3ee674933
relationship={
    me_uuid=f3c40674-01b2-4140-b5e9-c7187ac5f7e3
    other_uuid=e3f3c406-7401-4211-8035-e9c7187ac5f7
    friendship=6.18
    romance=0.3
    trust=5.14
    random_tick=8.17
    interactions=69
    status=PARENT
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=f3c40674-01b2-4140-b5e9-c7187ac5f7e3
    goodness=4.07
    shyness=3.82
    anxiety=2.55
    silliness=2.3
    laziness=5.35
    anger=5.1
    happiness=2.47
    weirdness=2.22
    craziness=6.09
    intelligence=3.66
    anger_mood=0.33
    anxiety_mood=9.42
    happiness_mood=4.97
    age=92.31
    height=4.39
    gender=MALE
    last_update=1.75019e+09
    goal=NONE
    working_on_goal=0
}
history=[
    good, i hoped you'd say as such
    father, what can I do for you?
    how about making me some food?
    oh ok i guess
]
