uuid=02eed977-4177-46c6-8098-d92e25cffe7d
relationship={
    me_uuid=7d938a69-02ee-4977-8177-36c6c098d92e
    other_uuid=a67d938a-6902-4ed9-b741-7736c6c098d9
    friendship=2.01
    romance=0.66
    trust=8.33
    random_tick=4.15
    interactions=53
    status=PARENT
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=7d938a69-02ee-4977-8177-36c6c098d92e
    goodness=4.34
    shyness=4.87
    anxiety=9.3
    silliness=4.23
    laziness=6.22
    anger=7.91
    happiness=9.9
    weirdness=5.91
    craziness=7.9
    intelligence=8.23
    anger_mood=0.22
    anxiety_mood=4.87
    happiness_mood=6.86
    age=139.11
    height=4.58
    gender=IN_BETWEEN
    last_update=1.7502e+09
    goal=ROB
    working_on_goal=1
}
history=[
    he said he'd help us with <POLITICAL_GOAL>
    oh great! maybe we should invite him to lunch or something
    how about we just meet him at <SECRET_CRIME_PLACE>
    oh yeah sure, sure
]
