uuid=03ca5a8f-db57-4385-b0c7-7e60f30ce688
relationship={
    me_uuid=1b4ac8ab-690a-43ca-9a8f-db57538570c7
    other_uuid=4ac8ab69-0a03-4a5a-8fdb-57538570c77e
    friendship=9.48
    romance=0.86
    trust=0.001
    random_tick=2.54
    interactions=36
    status=CHILD
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=1b4ac8ab-690a-43ca-9a8f-db57538570c7
    goodness=3.25
    shyness=0.86
    anxiety=5.27
    silliness=5.9
    laziness=5.37
    anger=5.26
    happiness=1.69
    weirdness=8.94
    craziness=3.69
    intelligence=3.06
    anger_mood=1.37
    anxiety_mood=0.74
    happiness_mood=4.73
    age=42.1
    height=2.99
    gender=FEMALE
    last_update=1.7502e+09
    goal=CONTROL
    working_on_goal=1
}
history=[
    oh right, yeah my bad. 
    don't worry about it
    hey could you introduce me to one of your high up friends?
    oh no i don't think so mom, that could ruin things for me
    oh ok
]
