uuid=048debdc-0191-4994-b39a-89e3d7eaa608
relationship={
    me_uuid=f7ffc623-9be2-4fc6-bf01-048debdc0191
    other_uuid=d1f7ffc6-239b-424f-863f-01048debdc01
    friendship=4.52
    romance=0.19
    trust=4.58
    random_tick=1.98
    interactions=10
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=f7ffc623-9be2-4fc6-bf01-048debdc0191
    goodness=3.51
    shyness=0.14
    anxiety=8.63
    silliness=5.26
    laziness=1.93
    anger=4.7
    happiness=8.17
    weirdness=8.46
    craziness=0.09
    intelligence=3.46
    anger_mood=7.79
    anxiety_mood=1.06
    happiness_mood=0.97
    age=8.34
    height=0.93
    gender=IN_BETWEEN
    last_update=1.75019e+09
    goal=ROB
    working_on_goal=1
}
history=[
    oh good! haha
    oh hey litle one
    hello old one?
    hey! haha
    have you seen any good stuff for sale today?
    no i don't think so, what're looking for?
    <VALUABLE_ITEM> mostly
    hmm, you'll have to check out the market then i guess
    ok bye!
    bye young one END
]
