uuid=0a03ca5a-8fdb-4753-8570-c77e60f30ce6
relationship={
    me_uuid=4ac8ab69-0a03-4a5a-8fdb-57538570c77e
    other_uuid=1b4ac8ab-690a-43ca-9a8f-db57538570c7
    friendship=1.05
    romance=0.98
    trust=7.57
    random_tick=5.29
    interactions=8
    status=PARENT
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=4ac8ab69-0a03-4a5a-8fdb-57538570c77e
    goodness=3.18
    shyness=6.79
    anxiety=0.14
    silliness=3.43
    laziness=6.78
    anger=3.19
    happiness=9.26
    weirdness=3.91
    craziness=9.98
    intelligence=1.05
    anger_mood=5.02
    anxiety_mood=1.69
    happiness_mood=4.38
    age=78.36
    height=0.56
    gender=FEMALE
    last_update=1.7502e+09
    goal=ROB
    working_on_goal=0
}
history=[
    oh right, yeah my bad. 
    don't worry about it
    hey could you introduce me to one of your high up friends?
    oh no i don't think so mom, that could ruin things for me
]
