uuid=0c1223f6-7147-4256-9b7c-5a5d8a288b0b
relationship={
    me_uuid=2a2298c0-2619-4e7c-8b2d-0c1223f67147
    other_uuid=282a2298-c026-490e-bc4b-2d0c1223f671
    friendship=5.58
    romance=0.77
    trust=0.86
    random_tick=9.42
    interactions=60
    status=BUSINESS_PARTNER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=2a2298c0-2619-4e7c-8b2d-0c1223f67147
    goodness=8.81
    shyness=9.58
    anxiety=7.85
    silliness=9.46
    laziness=2.57
    anger=4.18
    happiness=2.97
    weirdness=4.58
    craziness=3.29
    intelligence=2.18
    anger_mood=9.61
    anxiety_mood=8.5
    happiness_mood=1.61
    age=77.5
    height=1.37
    gender=IN_BETWEEN
    last_update=1.75019e+09
    goal=ROB
    working_on_goal=0
}
history=[
    ok sure
    what was that?
    i didn't say anything
    what haha. ok whatever, how do you fair?
    very well thanks. hey i got a new job, you want to join?
    no, i've enough with that craziness. i'm just a trader!
    ah come on! it's good!...ish i guess
    no thanks, though do you have any new goods for the shop?
    yep, here they are:
    oh great!
]
