uuid=0c37946a-df83-4555-bf9e-9525ccfdceba
relationship={
    me_uuid=235d3c86-d91f-4cfe-8c37-946adf830555
    other_uuid=5d3c86d9-1f4c-4e0c-b794-6adf830555ff
    friendship=3.4
    romance=0.62
    trust=2.18
    random_tick=0.1
    interactions=62
    status=CHILD
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=235d3c86-d91f-4cfe-8c37-946adf830555
    goodness=4.97
    shyness=5.74
    anxiety=0.81
    silliness=3.9
    laziness=8.33
    anger=6.38
    happiness=1.53
    weirdness=6.82
    craziness=0.41
    intelligence=5.7
    anger_mood=4.97
    anxiety_mood=0.26
    happiness_mood=5.69
    age=28.14
    height=0.93
    gender=MALE
    last_update=1.7502e+09
    goal=TRADE
    working_on_goal=1
}
history=[
    hello
    hey dad, what're you doing here today?
    oh just came to see you, was wondering if you wanted to hit the <FUN_PLACE>
    oh i have to work right now, though that does sound fun
    just take a break and come with me
    oh ok, i think i need a break
    that's the spirit! LEAD
]
