uuid=0ea43b18-a529-435f-aa7a-6bbbfcde0a3a
relationship={
    me_uuid=b3f1ec61-93f7-4ea4-bb18-a529a35f6a7a
    other_uuid=f1ec6193-f70e-443b-98a5-29a35f6a7a6b
    friendship=8.62
    romance=7.35
    trust=2.22
    random_tick=2.17
    interactions=430
    status=ENGAGED
    others_gender=MALE
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=b3f1ec61-93f7-4ea4-bb18-a529a35f6a7a
    goodness=4.89
    shyness=8.26
    anxiety=1.29
    silliness=4.66
    laziness=3.37
    anger=6.74
    happiness=5.03
    weirdness=4.5
    craziness=8.07
    intelligence=8.74
    anger_mood=4.39
    anxiety_mood=3.74
    happiness_mood=5.03
    age=55.1
    height=1.49
    gender=FEMALE
    last_update=1.75018e+09
}
history=[
    i'm dying haha
    wait what!
    only fooling
    oh ok, where have you been today?
    oh just wandering around really, been working some
]
