uuid=15524899-8d7a-4aac-839d-f62ba3a72174
relationship={
    me_uuid=c3fedbfd-6ce4-4061-9552-48998d7a1aac
    other_uuid=0bc3fedb-fd6c-4490-a115-5248998d7a1a
    friendship=9.42
    romance=0.51
    trust=4.5
    random_tick=1.77
    interactions=47
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=c3fedbfd-6ce4-4061-9552-48998d7a1aac
    goodness=5.59
    shyness=3.58
    anxiety=9.91
    silliness=7.9
    laziness=3.75
    anger=3.58
    happiness=9.61
    weirdness=0.22
    craziness=8.65
    intelligence=1.18
    anger_mood=3.37
    anxiety_mood=3.54
    happiness_mood=3.77
    age=49.94
    height=4.85
    gender=MALE
    last_update=1.75019e+09
    goal=FUN
    working_on_goal=0
}
history=[
    yeah sure sounds good. who are they again?
    hello <OTHER_NPC_NAME>!
    oh hello <OTHER_NPC_NAME>. how goes it?
    all good! what you have been up to?
    oh i've been <RECENT_ACTIVITY>
    haha good for you, never struck me you'd be into that
    yeah it's amazing, really amazing
    is that so? haha
]
