uuid=16b800b6-796e-4ec5-ac33-b2e3ca20937a
relationship={
    me_uuid=6598dfc5-16b8-40b6-b96e-9ec5ec33b2e3
    other_uuid=8f6598df-c516-4800-b679-6e9ec5ec33b2
    friendship=1.77
    romance=0.59
    trust=2.57
    random_tick=1.74
    interactions=6
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=6598dfc5-16b8-40b6-b96e-9ec5ec33b2e3
    goodness=5.1
    shyness=7.83
    anxiety=0.7
    silliness=0.95
    laziness=3.82
    anger=8.39
    happiness=1.26
    weirdness=0.15
    craziness=3.02
    intelligence=6.23
    anger_mood=9.1
    anxiety_mood=3.47
    happiness_mood=9.5
    age=97.65
    height=3.22
    gender=MALE
    last_update=1.75027e+09
    goal=NONE
    working_on_goal=0
}
history=[
    i love you KISS
    wo hey!
    oh poop you weren't who i though you were
    oh ok, well hands to yourself!
]
