uuid=190e7c4b-2d0c-4223-b671-4772561b7c5a
relationship={
    me_uuid=282a2298-c026-490e-bc4b-2d0c1223f671
    other_uuid=2a2298c0-2619-4e7c-8b2d-0c1223f67147
    friendship=2.62
    romance=0.23
    trust=0.62
    random_tick=9.45
    interactions=65
    status=BUSINESS_PARTNER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=282a2298-c026-490e-bc4b-2d0c1223f671
    goodness=8.25
    shyness=2.58
    anxiety=4.57
    silliness=8.9
    laziness=6.57
    anger=0.9
    happiness=1.91
    weirdness=8.58
    craziness=8.55
    intelligence=1.94
    anger_mood=9.51
    anxiety_mood=5.18
    happiness_mood=4.79
    age=32.46
    height=4.39
    gender=FEMALE
    last_update=1.75019e+09
    goal=TRADE
    working_on_goal=0
}
history=[
    ok sure
    what was that?
    i didn't say anything
    what haha. ok whatever, how do you fair?
    very well thanks. hey i got a new job, you want to join?
]
