uuid=1bdd9f74-b624-4780-856a-c32af8e8e763
relationship={
    me_uuid=abe0ea78-1bdd-4f74-b624-2780c56ac32a
    other_uuid=a6abe0ea-781b-4d9f-b4b6-242780c56ac3
    friendship=6
    romance=0.26
    trust=9
    random_tick=7.34
    interactions=77
    status=OTHER
    others_gender=FEMALE
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=abe0ea78-1bdd-4f74-b624-2780c56ac32a
    goodness=2.31
    shyness=4.38
    anxiety=1.03
    silliness=3.1
    laziness=4.07
    anger=6.14
    happiness=1.43
    weirdness=3.5
    craziness=3.11
    intelligence=5.18
    anger_mood=0.89
    anxiety_mood=1.18
    happiness_mood=0.89
    age=51.02
    height=2.57
    gender=MALE
    last_update=1.75017e+09
}
history=[
    you're a grandpa?
    very funny <OTHER_NPC_NAME>, are you a mule?
    haha no you old hag
    how do you fare <OTHER_NPC_NAME>?
]
