uuid=2251e772-f86c-4a54-9740-35c641f0376d
relationship={
    me_uuid=d57bcd43-2251-4772-b86c-2a54d74035c6
    other_uuid=4cd57bcd-4322-41e7-b2f8-6c2a54d74035
    friendship=0.3
    romance=0.81
    trust=3.1
    random_tick=8.23
    interactions=26
    status=OTHER
    others_gender=MALE
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=d57bcd43-2251-4772-b86c-2a54d74035c6
    goodness=4.47
    shyness=5.54
    anxiety=2.63
    silliness=5.54
    laziness=3.91
    anger=4.26
    happiness=9.51
    weirdness=7.5
    craziness=9.43
    intelligence=7.42
    anger_mood=3.67
    anxiety_mood=1.66
    happiness_mood=2
    age=86.22
    height=0.61
    gender=FEMALE
    last_update=1.75017e+09
}
history=[
    well why don't we pass some time walking round
    do you need some help?
    no but a cute young man would be nice
    oh freak! goodbye <OTHER_NPC_NAME>
]
