uuid=241527aa-1da4-4873-972d-9f84c3510cfa
relationship={
    me_uuid=754966a6-ad97-41e8-823e-241527aa1da4
    other_uuid=b6754966-a6ad-4771-a842-3e241527aa1d
    friendship=5.29
    romance=0.71
    trust=9.75
    random_tick=0.62
    interactions=98
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=754966a6-ad97-41e8-823e-241527aa1da4
    goodness=3.5
    shyness=7.83
    anxiety=2.62
    silliness=0.73
    laziness=4.06
    anger=4.97
    happiness=9.82
    weirdness=4.89
    craziness=0.1
    intelligence=0.49
    anger_mood=5.7
    anxiety_mood=1.77
    happiness_mood=7.08
    age=26.53
    height=3.02
    gender=FEMALE
    last_update=1.7502e+09
    goal=ROB
    working_on_goal=0
}
history=[
    can you do it for me?
    yeah sure one sec
    making the <FOOD> right?
    yep, ok ready MAKE <FOOD>
    FOLLOW
    ok here it is! GIVE <FOOD>
    oh thanks!
    yeah no problem!
    EAT <FOOD> you want some?
    sure
]
