uuid=2987a67f-2b4f-4ead-8899-710833ffd86e
relationship={
    me_uuid=866a7868-2987-467f-ab4f-cead48997108
    other_uuid=f5866a78-6829-47a6-bf2b-4fcead489971
    friendship=8.84
    romance=0.39
    trust=0.74
    random_tick=0.06
    interactions=58
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=866a7868-2987-467f-ab4f-cead48997108
    goodness=5.55
    shyness=8.3
    anxiety=1.35
    silliness=3.74
    laziness=1.11
    anger=3.5
    happiness=5.19
    weirdness=7.58
    craziness=3.59
    intelligence=5.98
    anger_mood=3.69
    anxiety_mood=8.7
    happiness_mood=6.65
    age=62.74
    height=3.29
    gender=IN_BETWEEN
    last_update=1.7502e+09
    goal=FUN
    working_on_goal=1
}
history=[
    nah I forgot haha
    you'll remember when we get there LEAD
    ok sounds fun
    are you coming?
]
