uuid=2c605c7e-cd14-4d4f-90c2-2b4ab30d3a18
relationship={
    me_uuid=cfda81d4-4818-4ca8-ac60-5c7ecd14dd4f
    other_uuid=13cfda81-d448-48fc-a82c-605c7ecd14dd
    friendship=5.74
    romance=5.85
    trust=0.78
    random_tick=2.07
    interactions=834
    status=ENGAGED
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=cfda81d4-4818-4ca8-ac60-5c7ecd14dd4f
    goodness=9.05
    shyness=4.74
    anxiety=7.83
    silliness=4.02
    laziness=2.87
    anger=8.98
    happiness=2.23
    weirdness=6.54
    craziness=5.91
    intelligence=0.22
    anger_mood=1.75
    anxiety_mood=8.78
    happiness_mood=9.51
    age=22.8
    height=4.59
    gender=IN_BETWEEN
    last_update=1.75019e+09
    goal=CONTROL
    working_on_goal=1
}
history=[
    it's the food isn't it!
    no the foods been great
    oh right, yeah my bad. 
    HUG
    hey let's go talk to <WORK_CONTACT>. We'll need their help
    yeah sure sounds good. who are they again?
    you don't remember?
    nah I forgot haha
]
