uuid=33b364cc-8808-4994-973c-b3be6dba6ea0
relationship={
    me_uuid=71cfd085-09f7-450d-b3b3-64cc8808c994
    other_uuid=cfd08509-f705-4d33-b364-cc8808c99417
    friendship=7.27
    romance=0.34
    trust=4.63
    random_tick=9.03
    interactions=76
    status=OTHER
    others_gender=MALE
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=71cfd085-09f7-450d-b3b3-64cc8808c994
    goodness=0.7
    shyness=6.71
    anxiety=3.74
    silliness=5.93
    laziness=1.1
    anger=4.25
    happiness=2.78
    weirdness=8.25
    craziness=1.22
    intelligence=5.13
    anger_mood=4
    anxiety_mood=5.05
    happiness_mood=5.3
    age=87.65
    height=4.9
    gender=MALE
    last_update=1.75017e+09
}
history=[
    why you?
    what do you mean you old fart?
    old fart! what
    yeah you old fart
    so how do you fare?
    oh fare enough, i found a new prospect for coins
    oh money is grand
]
