uuid=3a7c6f68-b2a1-4181-8f6f-6a6996f58cb5
relationship={
    me_uuid=4917a8d1-95a8-4a7c-af68-b2a111810f6f
    other_uuid=17a8d195-a83a-4c6f-a8b2-a111810f6f6a
    friendship=3
    romance=4
    trust=8.66
    random_tick=8.23
    interactions=95
    status=OTHER
    others_gender=MALE
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=4917a8d1-95a8-4a7c-af68-b2a111810f6f
    goodness=5.19
    shyness=9.02
    anxiety=1.19
    silliness=5.02
    laziness=1.51
    anger=5.34
    happiness=3.85
    weirdness=9.98
    craziness=4.89
    intelligence=8.94
    anger_mood=1
    anxiety_mood=2.22
    happiness_mood=4.01
    age=80.18
    height=3.09
    gender=FEMALE
    last_update=1.75017e+09
}
history=[
    what do you mean you old fart?
    old fart! what
    sorry <OTHER_NPC_NAME>. How do you fare?
    oh, i'm doing well. i see you at times here
    as do i, a fare lady is hard to come by
]
