uuid=4174f05c-a64f-4896-8b81-49a8f13dd9c5
relationship={
    me_uuid=9d3143b8-2de0-4496-8174-f05ca64fc896
    other_uuid=3143b82d-e0d4-4641-b4f0-5ca64fc8968b
    friendship=4.5
    romance=0.09
    trust=9.94
    random_tick=7.74
    interactions=27
    status=SIBLING
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=9d3143b8-2de0-4496-8174-f05ca64fc896
    goodness=0.55
    shyness=5.26
    anxiety=0.79
    silliness=5.5
    laziness=5.35
    anger=0.06
    happiness=1.43
    weirdness=8.86
    craziness=9.93
    intelligence=7.5
    anger_mood=6.97
    anxiety_mood=0.46
    happiness_mood=9.69
    age=12.26
    height=4.59
    gender=FEMALE
    last_update=1.75019e+09
    goal=CONTROL
    working_on_goal=0
}
history=[
    look who's talking
    hey anyway, can you go get me some food, i'm hungry
    can't you go get some?
    or you could go get me a <PET_ANIMAL>?
    haha you want a <PET_ANIMAL> now?
    yeah! they're cute
    why don't we just go see if we can find some outside?
]
