uuid=459f87a7-05fc-4c52-a139-8f79723e4e69
relationship={
    me_uuid=c8d28e38-223a-4c83-859f-87a705fcbc52
    other_uuid=d28e3822-3a2c-4345-9f87-a705fcbc52a1
    friendship=3.85
    romance=0.79
    trust=6.25
    random_tick=0.25
    interactions=73
    status=OTHER
    others_gender=FEMALE
    goal=GET_AWAY
    goal_asked_for=0
}
intelligence={
    uuid=c8d28e38-223a-4c83-859f-87a705fcbc52
    goodness=6.26
    shyness=5.27
    anxiety=4.74
    silliness=1.11
    laziness=8.9
    anger=1.27
    happiness=8.74
    weirdness=2.95
    craziness=2.7
    intelligence=8.95
    anger_mood=8.7
    anxiety_mood=10
    happiness_mood=9.02
    age=13.91
    height=1.16
    gender=MALE
    last_update=1.75017e+09
}
history=[
    hello handsome!
    haha, hi <OTHER_NPC_NAME>
    wait what is your name again?
    <NPC_NAME>
    oh that's right! the handsome man that took me for a stroll last evening
    haha, uh no, listen I got to go
    wait at least one kiss for me
]
