uuid=477b8f43-6aa0-4e73-802b-cdae3498f7e8
relationship={
    me_uuid=aee51622-45c5-477b-8f43-6aa0ee73402b
    other_uuid=e5162245-c547-4b8f-836a-a0ee73402bcd
    friendship=7.42
    romance=5.02
    trust=2.7
    random_tick=1.13
    interactions=225
    status=MARRIED
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=aee51622-45c5-477b-8f43-6aa0ee73402b
    goodness=9.45
    shyness=5.62
    anxiety=8.49
    silliness=4.66
    laziness=3.21
    anger=9.38
    happiness=3.61
    weirdness=9.78
    craziness=6.47
    intelligence=5.86
    anger_mood=4.71
    anxiety_mood=7.62
    happiness_mood=7.27
    age=33
    height=1.77
    gender=MALE
    last_update=1.75019e+09
    goal=NONE
    working_on_goal=1
}
history=[
    old fart! what
    who are you talking about?
    i thought you said that
    oh nope haha
    hey <OTHER_NPC_NAME>, come here
]
