uuid=4b8f5a8f-bb7d-4320-8da8-b9f00a281c51
relationship={
    me_uuid=84dd6a12-cbfc-4b8f-9a8f-bb7de3200da8
    other_uuid=dd6a12cb-fc4b-4f5a-8fbb-7de3200da8b9
    friendship=1
    romance=0.14
    trust=3.93
    random_tick=7.02
    interactions=76
    status=OTHER
    others_gender=FEMALE
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=84dd6a12-cbfc-4b8f-9a8f-bb7de3200da8
    goodness=6.02
    shyness=4.09
    anxiety=6.1
    silliness=6.31
    laziness=1.86
    anger=7.11
    happiness=8.34
    weirdness=5.43
    craziness=0.02
    intelligence=8.07
    anger_mood=8.78
    anxiety_mood=5.03
    happiness_mood=5
    age=36.31
    height=2.02
    gender=IN_BETWEEN
    last_update=1.74977e+09
}
history=[
    care to pass some time with an old woman?
    what haha
    i'm pretending!
    oh ok, are you a grandma?
    yes!
]
