uuid=4cb5d623-8bcc-47fa-b668-2b03ffde1c73
relationship={
    me_uuid=22da665d-2c85-4cb5-9623-8bccc7fa3668
    other_uuid=da665d2c-854c-45d6-a38b-ccc7fa36682b
    friendship=2.63
    romance=0.42
    trust=3.91
    random_tick=6.46
    interactions=38
    status=OTHER
    others_gender=MALE
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=22da665d-2c85-4cb5-9623-8bccc7fa3668
    goodness=6.54
    shyness=8.57
    anxiety=3.5
    silliness=7.29
    laziness=5.22
    anger=1.69
    happiness=9.62
    weirdness=1.77
    craziness=9.7
    intelligence=7.53
    anger_mood=5.46
    anxiety_mood=1.45
    happiness_mood=7
    age=47.13
    height=4.84
    gender=FEMALE
    last_update=1.75017e+09
}
history=[
    I've felt sad lately, it's terrible
    oh me too, it's in the food!
    haha, it's not the food <OTHER_NPC_NAME>
    no? i could have sworn. you sure?
    aye, though i do feel a little better now
]
