uuid=5bcc5a05-ac07-4eb8-8198-655f4bbcf431
relationship={
    me_uuid=337de44f-bfb6-4bcc-9a05-ac07feb84198
    other_uuid=22337de4-4fbf-465b-8c5a-05ac07feb841
    friendship=7
    romance=0
    trust=2.31
    random_tick=2.86
    interactions=88
    status=OTHER
    others_gender=FEMALE
    goal=FRIEND
    goal_asked_for=0
}
intelligence={
    uuid=337de44f-bfb6-4bcc-9a05-ac07feb84198
    goodness=0.38
    shyness=5.61
    anxiety=2.86
    silliness=4.81
    laziness=6.38
    anger=8.25
    happiness=7.06
    weirdness=7.37
    craziness=6.18
    intelligence=2.17
    anger_mood=0.98
    anxiety_mood=2.65
    happiness_mood=1
    age=46.81
    height=2.12
    gender=MALE
    last_update=1.74977e+09
}
history=[
    hi!
    hello
    how do you do?
    not well i'm afraid
    what a shame
    care to pass some time with an old woman?
]
