uuid=5ca64fc8-968b-4149-a8f1-3dd9c542ac6b
relationship={
    me_uuid=3143b82d-e0d4-4641-b4f0-5ca64fc8968b
    other_uuid=9d3143b8-2de0-4496-8174-f05ca64fc896
    friendship=8.41
    romance=0.94
    trust=6.81
    random_tick=7.5
    interactions=60
    status=SIBLING
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=3143b82d-e0d4-4641-b4f0-5ca64fc8968b
    goodness=8.98
    shyness=9.99
    anxiety=6.02
    silliness=7.27
    laziness=7.42
    anger=8.87
    happiness=9.02
    weirdness=4.79
    craziness=4.94
    intelligence=5.03
    anger_mood=5.18
    anxiety_mood=9.59
    happiness_mood=9.74
    age=19.775
    height=2.08
    gender=MALE
    last_update=1.75019e+09
    goal=NONE
    working_on_goal=0
}
history=[
    look who's talking
    hey anyway, can you go get me some food, i'm hungry
    can't you go get some?
    or you could go get me a <PET_ANIMAL>?
    haha you want a <PET_ANIMAL> now?
    yeah! they're cute
    why don't we just go see if we can find some outside?
    can you do it for me?
    ok no, but I can help you
    well ok, let's go LEAD
]
