uuid=605c7ecd-14dd-4fd0-822b-4ab30d3a18e1
relationship={
    me_uuid=13cfda81-d448-48fc-a82c-605c7ecd14dd
    other_uuid=cfda81d4-4818-4ca8-ac60-5c7ecd14dd4f
    friendship=0.98
    romance=8.18
    trust=3.22
    random_tick=2.49
    interactions=834
    status=ENGAGED
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=13cfda81-d448-48fc-a82c-605c7ecd14dd
    goodness=9.99
    shyness=9.74
    anxiety=7.35
    silliness=8.94
    laziness=5.11
    anger=6.7
    happiness=7.19
    weirdness=8.78
    craziness=3.59
    intelligence=5.18
    anger_mood=5.69
    anxiety_mood=6
    happiness_mood=0.65
    age=23.52
    height=3.29
    gender=IN_BETWEEN
    last_update=1.75019e+09
    goal=CONTROL
    working_on_goal=1
}
history=[
    it's the food isn't it!
    no the foods been great
    oh right, yeah my bad. 
    HUG
    hey let's go talk to <WORK_CONTACT>. We'll need their help
    yeah sure sounds good. who are they again?
    you don't remember?
    nah I forgot haha
    you'll remember when we get there LEAD
]
