uuid=68b2a111-810f-4f6a-a996-f58cb5cfeae1
relationship={
    me_uuid=17a8d195-a83a-4c6f-a8b2-a111810f6f6a
    other_uuid=4917a8d1-95a8-4a7c-af68-b2a111810f6f
    friendship=4.09
    romance=4
    trust=6.89
    random_tick=2.79
    interactions=25
    status=OTHER
    others_gender=FEMALE
    goal=ROMANCE
    goal_asked_for=0
}
intelligence={
    uuid=17a8d195-a83a-4c6f-a8b2-a111810f6f6a
    goodness=0.1
    shyness=3.27
    anxiety=7.22
    silliness=0.47
    laziness=0.02
    anger=1.99
    happiness=8.5
    weirdness=7.83
    craziness=3.5
    intelligence=7.99
    anger_mood=3.66
    anxiety_mood=0.23
    happiness_mood=8.62
    age=85.47
    height=3.86
    gender=MALE
    last_update=1.75017e+09
}
history=[
    what do you mean you old fart?
    old fart! what
    sorry <OTHER_NPC_NAME>. How do you fare?
    oh, i'm doing well. i see you at times here
    as do i, a fare lady is hard to come by
    oh yes I suppose
    care to join me for stroll?
    i suppose i could
]
