uuid=694b3789-35c6-4553-9e6a-5abfa49608c5
relationship={
    me_uuid=336e3c34-2e7d-494b-b789-35c635535e6a
    other_uuid=6e3c342e-7d69-4b37-8935-c635535e6a5a
    friendship=0.78
    romance=0.79
    trust=5.19
    random_tick=4.41
    interactions=71
    status=ENEMY
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=336e3c34-2e7d-494b-b789-35c635535e6a
    goodness=5.18
    shyness=7.43
    anxiety=6.62
    silliness=0.81
    laziness=8.38
    anger=3.45
    happiness=8.46
    weirdness=7.61
    craziness=4.3
    intelligence=7.45
    anger_mood=6.64
    anxiety_mood=2.97
    happiness_mood=1.06
    age=79.17
    height=4.76
    gender=MALE
    last_update=1.75027e+09
    goal=NONE
    working_on_goal=0
}
history=[
    oh you know, help understand things
    in what way?
    you wouldn't understand haha
    ha! try me!
    END
]
