uuid=6aa0ee73-402b-4dae-b498-f7e8596cae48
relationship={
    me_uuid=aee51622-45c5-477b-8f43-6aa0ee73402b
    other_uuid=e5162245-c547-4b8f-836a-a0ee73402bcd
    friendship=7.42
    romance=5.32
    trust=2.7
    random_tick=8.87
    interactions=225
    status=MARRIED
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=aee51622-45c5-477b-8f43-6aa0ee73402b
    goodness=9.45
    shyness=5.62
    anxiety=8.49
    silliness=4.66
    laziness=3.21
    anger=9.38
    happiness=3.61
    weirdness=9.78
    craziness=6.47
    intelligence=5.86
    anger_mood=3.71
    anxiety_mood=7.62
    happiness_mood=7.37
    age=33
    height=1.77
    gender=MALE
    last_update=1.75019e+09
    goal=NONE
    working_on_goal=1
}
history=[
    old fart! what
    who are you talking about?
    i thought you said that
    oh nope haha
    hey <OTHER_NPC_NAME>, come here
    what? GO_TO <OTHER_NPC_NAME>
    i love you HUG
    oh I love you too KISS HUG
    KISS
]
