uuid=6c6938ad-105d-4bc0-8c78-54074cf23c00
relationship={
    me_uuid=7d98a3e0-e36c-484e-ac69-38ad105dfbc0
    other_uuid=98a3e0e3-6c98-4e6c-a938-ad105dfbc00c
    friendship=0.3
    romance=8.99
    trust=2.88
    random_tick=5.82
    interactions=445
    status=MARRIED
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=7d98a3e0-e36c-484e-ac69-38ad105dfbc0
    goodness=2.75
    shyness=9.62
    anxiety=7.43
    silliness=3.54
    laziness=9.91
    anger=1.06
    happiness=6.71
    weirdness=1.9
    craziness=7.83
    intelligence=3.02
    anger_mood=3.47
    anxiety_mood=8.46
    happiness_mood=3.03
    age=49.5
    height=3.11
    gender=IN_BETWEEN
    last_update=1.7502e+09
    goal=TRADE
    working_on_goal=0
}
history=[
    you're beautiful <OTHER_NPC_NAME>
    i love you KISS
    KISS HUG
    hey were is the <FOOD>
    oh i don't know
    did you use it recently?
    i don't think so, did you?
]
