uuid=6c984e6c-6938-4d10-9dfb-c00c7854074c
relationship={
    me_uuid=98a3e0e3-6c98-4e6c-a938-ad105dfbc00c
    other_uuid=7d98a3e0-e36c-484e-ac69-38ad105dfbc0
    friendship=3.6
    romance=7.74
    trust=3.56
    random_tick=1.83
    interactions=445
    status=MARRIED
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=98a3e0e3-6c98-4e6c-a938-ad105dfbc00c
    goodness=5.23
    shyness=9.3
    anxiety=1.77
    silliness=3.86
    laziness=2.01
    anger=4.1
    happiness=7.93
    weirdness=0.02
    craziness=9.53
    intelligence=1.62
    anger_mood=7.03
    anxiety_mood=8.5
    happiness_mood=9.51
    age=48
    height=0.81
    gender=IN_BETWEEN
    last_update=1.7502e+09
    goal=CONTROL
    working_on_goal=1
}
history=[
    you're beautiful <OTHER_NPC_NAME>
    i love you KISS
    KISS HUG
    hey were is the <FOOD>
]
