uuid=763c46de-5256-4a56-a140-460e6b4c3e5d
relationship={
    me_uuid=60867d20-397a-4250-bbc3-763c46de5256
    other_uuid=867d2039-7a42-403b-8376-3c46de52563a
    friendship=2.31
    romance=0.65
    trust=1.99
    random_tick=6.02
    interactions=51
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=60867d20-397a-4250-bbc3-763c46de5256
    goodness=9.5
    shyness=8.15
    anxiety=7.9
    silliness=0.87
    laziness=0.62
    anger=2.09
    happiness=7.66
    weirdness=0.73
    craziness=9.02
    intelligence=5.05
    anger_mood=5
    anxiety_mood=5.05
    happiness_mood=5.3
    age=56.73
    height=1.98
    gender=MALE
    last_update=1.75019e+09
    goal=NONE
    working_on_goal=0
}
history=[
    i told them about the food!
    oh hello <OTHER_NPC_NAME>
    oh hey <OTHER_NPC_NAME>
    what have you been up too?
    oh you know, the usual
    oh really, what's the usual?
    meh, you know just hanging out
    oh ok, well nice to see young people like you around
    i'm not that young
]
