uuid=7a42503b-c376-4c46-9e52-563a56214046
relationship={
    me_uuid=867d2039-7a42-403b-8376-3c46de52563a
    other_uuid=60867d20-397a-4250-bbc3-763c46de5256
    friendship=9.53
    romance=0.7
    trust=5.21
    random_tick=0.23
    interactions=89
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=867d2039-7a42-403b-8376-3c46de52563a
    goodness=0.34
    shyness=9.03
    anxiety=4.66
    silliness=9.03
    laziness=1.5
    anger=3.35
    happiness=5.82
    weirdness=5.27
    craziness=0.46
    intelligence=3.67
    anger_mood=8.86
    anxiety_mood=6.39
    happiness_mood=1.58
    age=12.57
    height=2.12
    gender=MALE
    last_update=1.75019e+09
    goal=NONE
    working_on_goal=0
}
history=[
    i told them about the food!
    oh hello <OTHER_NPC_NAME>
    oh hey <OTHER_NPC_NAME>
    what have you been up too?
]
