uuid=7ce38a5f-7463-44c1-814e-f3e8f440e13f
relationship={
    me_uuid=cd2e9c94-3e76-4864-aba1-d12c7ce38a5f
    other_uuid=2e9c943e-7608-44eb-a1d1-2c7ce38a5f74
    friendship=3.13
    romance=0.14
    trust=8.57
    random_tick=3.19
    interactions=79
    status=CHILD
    others_gender=MALE
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=cd2e9c94-3e76-4864-aba1-d12c7ce38a5f
    goodness=2.82
    shyness=1.75
    anxiety=8.26
    silliness=8.07
    laziness=1.94
    anger=8.71
    happiness=1.3
    weirdness=3.67
    craziness=9.82
    intelligence=2.95
    anger_mood=9.9
    anxiety_mood=6.55
    happiness_mood=2.7
    age=62.47
    height=3.62
    gender=FEMALE
    last_update=1.75018e+09
}
history=[
    what? you're so dumb sometimes
    look who's talking
    oh sorry, i don't know why i said that
    oh ok whatever
    so how are things my daughter
    all's well father
    oh good, it always pleases me to here that
    father, why don't you make us a ship sometime
    hmm, i guess i could do that. i'm rather handy
    yeah maybe we could make some money selling <INVENTORY_ITEM>
    oh but i'm so old. i'm just a poop
]
