uuid=7d694b37-8935-4635-935e-6a5abfa49608
relationship={
    me_uuid=6e3c342e-7d69-4b37-8935-c635535e6a5a
    other_uuid=336e3c34-2e7d-494b-b789-35c635535e6a
    friendship=0.15
    romance=0.35
    trust=5.78
    random_tick=0.38
    interactions=27
    status=ENEMY
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=6e3c342e-7d69-4b37-8935-c635535e6a5a
    goodness=3.17
    shyness=5.82
    anxiety=5.67
    silliness=0.3
    laziness=4.47
    anger=9.1
    happiness=7.59
    weirdness=2.22
    craziness=5.03
    intelligence=9.66
    anger_mood=3.21
    anxiety_mood=1.42
    happiness_mood=8.65
    age=48.06
    height=3.59
    gender=FEMALE
    last_update=1.75027e+09
    goal=ROB
    working_on_goal=0
}
history=[
    oh you know, help understand things
    in what way?
    you wouldn't understand haha
    ha! try me!
]
