uuid=7de3200d-a8b9-400a-a81c-513230aea523
relationship={
    me_uuid=dd6a12cb-fc4b-4f5a-8fbb-7de3200da8b9
    other_uuid=84dd6a12-cbfc-4b8f-9a8f-bb7de3200da8
    friendship=4
    romance=0.66
    trust=8.1
    random_tick=5.38
    interactions=68
    status=OTHER
    others_gender=IN_BETWEEN
    goal=FUN
    goal_asked_for=0
}
intelligence={
    uuid=dd6a12cb-fc4b-4f5a-8fbb-7de3200da8b9
    goodness=2.65
    shyness=9.9
    anxiety=6.09
    silliness=6.46
    laziness=5.21
    anger=2.66
    happiness=0.01
    weirdness=7.46
    craziness=0.49
    intelligence=7.94
    anger_mood=6
    anxiety_mood=4.1
    happiness_mood=8.49
    age=5.94
    height=2.15
    gender=FEMALE
    last_update=1.74977e+09
}
history=[
    care to pass some time with an old woman?
    what haha
    i'm pretending!
    oh ok, are you a grandma?
    yes!
    oh wow
    do you want to play?
    ok sure
    ok good
    who should I pretend to be?
]
