uuid=83459f87-a705-4cbc-92a1-398f79723e4e
relationship={
    me_uuid=d28e3822-3a2c-4345-9f87-a705fcbc52a1
    other_uuid=c8d28e38-223a-4c83-859f-87a705fcbc52
    friendship=3.94
    romance=0.43
    trust=3.66
    random_tick=0.57
    interactions=34
    status=OTHER
    others_gender=MALE
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=d28e3822-3a2c-4345-9f87-a705fcbc52a1
    goodness=4.33
    shyness=5.42
    anxiety=9.13
    silliness=6.66
    laziness=3.13
    anger=0.66
    happiness=2.81
    weirdness=0.34
    craziness=8.17
    intelligence=5.7
    anger_mood=9.21
    anxiety_mood=6
    happiness_mood=0.23
    age=78.46
    height=3.33
    gender=FEMALE
    last_update=1.75017e+09
}
history=[
    hello handsome!
    haha, hi <OTHER_NPC_NAME>
    wait what is your name again?
    <NPC_NAME>
    oh that's right! the handsome man that took me for a stroll last evening
    haha, uh no, listen I got to go
]
