uuid=87808ddc-370f-475b-87be-947e5bd7d54f
relationship={
    me_uuid=b9f2c08c-55f2-4c96-8780-8ddc370fa75b
    other_uuid=f2c08c55-f22c-4687-808d-dc370fa75b07
    friendship=4.6
    romance=6.87
    trust=6.7
    random_tick=2.42
    interactions=26
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=b9f2c08c-55f2-4c96-8780-8ddc370fa75b
    goodness=7.53
    shyness=9.98
    anxiety=6.81
    silliness=0.7
    laziness=1.77
    anger=4.26
    happiness=2.41
    weirdness=4.9
    craziness=8.73
    intelligence=1.22
    anger_mood=0.73
    anxiety_mood=3.42
    happiness_mood=8.41
    age=81.9
    height=0.77
    gender=MALE
    last_update=1.75019e+09
    goal=TRADE
    working_on_goal=1
}
history=[
    so how are things my daughter
    daughter haha
    oh you old fellow! where have you been all this time
    you're beautiful <OTHER_NPC_NAME>
    oh you thank you
    i always hoped I could find a girl like you
    hey, how about taking a lady for a stroll?
]
