uuid=87a67f2b-4fce-4d48-9971-0833ffd86ea0
relationship={
    me_uuid=f5866a78-6829-47a6-bf2b-4fcead489971
    other_uuid=866a7868-2987-467f-ab4f-cead48997108
    friendship=6.49
    romance=0.11
    trust=6.71
    random_tick=9.29
    interactions=88
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=f5866a78-6829-47a6-bf2b-4fcead489971
    goodness=4.22
    shyness=7.67
    anxiety=4.62
    silliness=0.39
    laziness=7.34
    anger=2.57
    happiness=4.38
    weirdness=1.21
    craziness=5.74
    intelligence=6.89
    anger_mood=7.22
    anxiety_mood=1.45
    happiness_mood=1.78
    age=26.69
    height=1.52
    gender=FEMALE
    last_update=1.7502e+09
    goal=CONTROL
    working_on_goal=1
}
history=[
    nah I forgot haha
    you'll remember when we get there LEAD
    ok sounds fun
    are you coming?
    oh yep sorry, got distracted
]
