uuid=8cecbc69-c5ad-4033-8418-767d4b0054b3
relationship={
    me_uuid=d78fbdcb-24a3-40c4-bab9-9f618cecbc69
    other_uuid=ddd78fbd-cb24-43e0-847a-b99f618cecbc
    friendship=3.36
    romance=0.74
    trust=1.58
    random_tick=7.37
    interactions=83
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=d78fbdcb-24a3-40c4-bab9-9f618cecbc69
    goodness=1.13
    shyness=5.86
    anxiety=7.13
    silliness=1.86
    laziness=8.81
    anger=3.54
    happiness=9.99
    weirdness=0.9
    craziness=6.95
    intelligence=3.94
    anger_mood=5.19
    anxiety_mood=3.18
    happiness_mood=6.33
    age=17.22
    height=0.59
    gender=MALE
    last_update=1.75019e+09
    goal=FUN
    working_on_goal=1
}
history=[
    well there's been a recent sell off, you probably don't want to pass this up
    oh hey
    oh there you are, want to try something
    nope!
    why not? it's fun
    i don't trust you haha
    ah man ok, well at least tell me something funny
    ok well, let me think
    
    food makes you fat, music makes you deaf, art makes you crazy
    haha alright i guess so
    so did you trick anyone today? and I know that's what you do haha
]
