uuid=92e5eb97-9236-42c9-b541-2f391d51cba5
relationship={
    me_uuid=99c3c745-bef7-4095-92e5-eb979236b2c9
    other_uuid=c3c745be-f7f0-4592-a5eb-979236b2c9f5
    friendship=1.29
    romance=0.98
    trust=2.89
    random_tick=9.83
    interactions=22
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=99c3c745-bef7-4095-92e5-eb979236b2c9
    goodness=1.46
    shyness=1.91
    anxiety=1.7
    silliness=5.99
    laziness=7.62
    anger=4.39
    happiness=9.22
    weirdness=7.11
    craziness=9.66
    intelligence=4.15
    anger_mood=6.7
    anxiety_mood=5.51
    happiness_mood=8.06
    age=38.43
    height=3.2
    gender=MALE
    last_update=1.75019e+09
    goal=TRADE
    working_on_goal=1
}
history=[
    oh yes I suppose
    i have <INVENTORY_ITEM>, sold at <EVIL_PRICE>. A real bargain
    that's not a good price
    you don't think so?
    no i've seen much better
    well there's been a recent sell off, you probably don't want to pass this up
    i'll take my chances
]
