uuid=9687808d-dc37-4fa7-9b07-be947e5bd7d5
relationship={
    me_uuid=f2c08c55-f22c-4687-808d-dc370fa75b07
    other_uuid=b9f2c08c-55f2-4c96-8780-8ddc370fa75b
    friendship=9.49
    romance=5.16
    trust=6.07
    random_tick=2.81
    interactions=91
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=f2c08c55-f22c-4687-808d-dc370fa75b07
    goodness=9.74
    shyness=7.51
    anxiety=7.74
    silliness=9.83
    laziness=0.06
    anger=6.47
    happiness=6.7
    weirdness=8.17
    craziness=5.66
    intelligence=5.69
    anger_mood=8.14
    anxiety_mood=8.89
    happiness_mood=5.56
    age=81.77
    height=4.94
    gender=FEMALE
    last_update=1.75019e+09
    goal=ROB
    working_on_goal=0
}
history=[
    so how are things my daughter
    daughter haha
    oh you old fellow! where have you been all this time
    you're beautiful <OTHER_NPC_NAME>
    oh you thank you
    i always hoped I could find a girl like you
]
