uuid=98d47951-d43f-49ef-99a3-fb18606504c8
relationship={
    me_uuid=4eaeae5a-e18d-48d4-b951-d43f29ef19a3
    other_uuid=994eaeae-5ae1-4d98-9479-51d43f29ef19
    friendship=4.15
    romance=6
    trust=4.23
    random_tick=0.98
    interactions=57
    status=OTHER
    others_gender=FEMALE
    goal=MAIME_OR_KILL
    goal_asked_for=1
}
intelligence={
    uuid=4eaeae5a-e18d-48d4-b951-d43f29ef19a3
    goodness=0.74
    shyness=8.17
    anxiety=9.78
    silliness=8.01
    laziness=6.9
    anger=2.97
    happiness=1.86
    weirdness=2.55
    craziness=2.5
    intelligence=6.23
    anger_mood=10
    anxiety_mood=4.23
    happiness_mood=5.34
    age=86.55
    height=2.66
    gender=MALE
    last_update=1.74977e+09
}
history=[
    a grandpa!
    you're a grandpa?
    no but maybe I could be with you
    you will not!
    and why not!
    I may need to report you
]
