uuid=a1a3fe74-936c-4628-ae44-4a820bb6bfd6
relationship={
    me_uuid=81925b40-6f69-41a3-be74-936c2628ae44
    other_uuid=925b406f-69a1-43fe-b493-6c2628ae444a
    friendship=5.1
    romance=0.3
    trust=2.46
    random_tick=7.5
    interactions=84
    status=OTHER
    others_gender=FEMALE
    goal=GET_AWAY
    goal_asked_for=0
}
intelligence={
    uuid=81925b40-6f69-41a3-be74-936c2628ae44
    goodness=9.37
    shyness=3.22
    anxiety=3.77
    silliness=7.62
    laziness=3.85
    anger=7.7
    happiness=9.61
    weirdness=3.46
    craziness=9.11
    intelligence=7.3
    anger_mood=9
    anxiety_mood=7.22
    happiness_mood=3.59
    age=66.34
    height=4.81
    gender=IN_BETWEEN
    last_update=1.75017e+09
}
history=[
    oh ok, are you a grandma?
    not really
    oh haha, my bad
    
    hey where are you going?
]
