uuid=a1d12c7c-e38a-4f74-a3e4-c1c14ef3e8f4
relationship={
    me_uuid=2e9c943e-7608-44eb-a1d1-2c7ce38a5f74
    other_uuid=cd2e9c94-3e76-4864-aba1-d12c7ce38a5f
    friendship=9.43
    romance=0.37
    trust=6.95
    random_tick=3.59
    interactions=68
    status=PARENT
    others_gender=FEMALE
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=2e9c943e-7608-44eb-a1d1-2c7ce38a5f74
    goodness=8.3
    shyness=6.49
    anxiety=8.5
    silliness=8.97
    laziness=0.98
    anger=7.13
    happiness=9.14
    weirdness=0.97
    craziness=2.98
    intelligence=0.49
    anger_mood=2.5
    anxiety_mood=2.79
    happiness_mood=2.66
    age=89.42
    height=3.6
    gender=MALE
    last_update=1.75018e+09
}
history=[
    what? you're so dumb sometimes
    look who's talking
    oh sorry, i don't know why i said that
    oh ok whatever
    so how are things my daughter
    all's well father
    oh good, it always pleases me to here that
    father, why don't you make us a ship sometime
]
