uuid=a43b18a5-29a3-4f6a-ba6b-bbfcde0a3a48
relationship={
    me_uuid=f1ec6193-f70e-443b-98a5-29a35f6a7a6b
    other_uuid=b3f1ec61-93f7-4ea4-bb18-a529a35f6a7a
    friendship=6.71
    romance=9.26
    trust=1.27
    random_tick=4.65
    interactions=430
    status=ENGAGED
    others_gender=FEMALE
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=f1ec6193-f70e-443b-98a5-29a35f6a7a6b
    goodness=2.38
    shyness=0.41
    anxiety=1.66
    silliness=4.09
    laziness=2.02
    anger=3.45
    happiness=1.38
    weirdness=8.49
    craziness=6.42
    intelligence=9.21
    anger_mood=7.14
    anxiety_mood=5.61
    happiness_mood=3.54
    age=55.68
    height=2.62
    gender=MALE
    last_update=1.75018e+09
}
history=[
    i'm dying haha
    wait what!
    only fooling
    oh ok, where have you been today?
    oh just wandering around really, been working some
    oh ok, HUG
]
