uuid=a7f8e0ca-9075-4c33-9fcc-efa8e5d44f2e
relationship={
    me_uuid=7ab8b789-a7f8-40ca-9075-dc33dfccefa8
    other_uuid=937ab8b7-89a7-48e0-8a90-75dc33dfccef
    friendship=5.62
    romance=8.24
    trust=5.91
    random_tick=0.65
    interactions=52
    status=FRIEND
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=7ab8b789-a7f8-40ca-9075-dc33dfccefa8
    goodness=4.46
    shyness=5.69
    anxiety=3.58
    silliness=0.25
    laziness=0.98
    anger=0.49
    happiness=1.22
    weirdness=7.85
    craziness=5.86
    intelligence=4.01
    anger_mood=2.02
    anxiety_mood=5.85
    happiness_mood=3.86
    age=82.79
    height=3.38
    gender=FEMALE
    last_update=1.75027e+09
    goal=NONE
    working_on_goal=0
}
history=[
    hey no hitting little one
    hi <OTHER_NPC_NAME>
    oh hello! you look rather dashing today <OTHER_NPC_NAME>
    oh thanks
]
