uuid=aa1da4f8-7397-4d9f-84c3-510cfa42d5ee
relationship={
    me_uuid=b6754966-a6ad-4771-a842-3e241527aa1d
    other_uuid=754966a6-ad97-41e8-823e-241527aa1da4
    friendship=6.84
    romance=0.74
    trust=5.26
    random_tick=1.37
    interactions=52
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=b6754966-a6ad-4771-a842-3e241527aa1d
    goodness=5.53
    shyness=3.54
    anxiety=5.85
    silliness=3.86
    laziness=1.85
    anger=9.86
    happiness=3.29
    weirdness=1.22
    craziness=0.49
    intelligence=8.42
    anger_mood=3.37
    anxiety_mood=1.3
    happiness_mood=4.23
    age=85.86
    height=3.99
    gender=FEMALE
    last_update=1.7502e+09
    goal=TRADE
    working_on_goal=1
}
history=[
    can you do it for me?
    yeah sure one sec
    making the <FOOD> right?
    yep, ok ready MAKE <FOOD>
    FOLLOW
    ok here it is! GIVE <FOOD>
    oh thanks!
    yeah no problem!
    EAT <FOOD> you want some?
    sure
    GIVE <FOOD> here you go
    yummy EAT <FOOD>
    FART
]
