uuid=b2114035-e9c7-487a-85f7-e3ee67493390
relationship={
    me_uuid=e3f3c406-7401-4211-8035-e9c7187ac5f7
    other_uuid=f3c40674-01b2-4140-b5e9-c7187ac5f7e3
    friendship=5.27
    romance=0.1
    trust=0.07
    random_tick=0.14
    interactions=89
    status=CHILD
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=e3f3c406-7401-4211-8035-e9c7187ac5f7
    goodness=5.34
    shyness=7.53
    anxiety=6.78
    silliness=1.77
    laziness=2.54
    anger=0.49
    happiness=6.54
    weirdness=0.65
    craziness=3.62
    intelligence=6.49
    anger_mood=9.46
    anxiety_mood=8.01
    happiness_mood=0.98
    age=76.21
    height=1.18
    gender=FEMALE
    last_update=1.75019e+09
    goal=FUN
    working_on_goal=0
}
history=[
    good, i hoped you'd say as such
    father, what can I do for you?
    how about making me some food?
    oh ok i guess
    make my favorite if that's ok
]
