uuid=c3a5108d-2e87-4af7-bd6f-9e9325c511cf
relationship={
    me_uuid=2828c31d-c3a5-408d-ae87-eaf7bd6f9e93
    other_uuid=f22828c3-1dc3-4510-8d2e-87eaf7bd6f9e
    friendship=8.98
    romance=0.07
    trust=8.98
    random_tick=4.46
    interactions=34
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=2828c31d-c3a5-408d-ae87-eaf7bd6f9e93
    goodness=4.59
    shyness=5.9
    anxiety=5.03
    silliness=1.58
    laziness=5.03
    anger=1.58
    happiness=0.65
    weirdness=5.9
    craziness=3.45
    intelligence=5.82
    anger_mood=5.05
    anxiety_mood=5.78
    happiness_mood=2.33
    age=53.06
    height=3.29
    gender=MALE
    last_update=1.7502e+09
    goal=ROB
    working_on_goal=0
}
history=[
    haha no. what've you been doing today?
    oh not much, got the better of some guy earlier
    oh cool did you get anything?
    yeah a few <VALUABLE_ITEM>
]
