uuid=c47ab99f-618c-4cbc-a9c5-ad8033c41876
relationship={
    me_uuid=ddd78fbd-cb24-43e0-847a-b99f618cecbc
    other_uuid=d78fbdcb-24a3-40c4-bab9-9f618cecbc69
    friendship=1.94
    romance=0.13
    trust=0.9
    random_tick=6.06
    interactions=70
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=ddd78fbd-cb24-43e0-847a-b99f618cecbc
    goodness=8.87
    shyness=7.46
    anxiety=0.07
    silliness=2.62
    laziness=1.11
    anger=3.66
    happiness=6.47
    weirdness=9.02
    craziness=6.15
    intelligence=8.7
    anger_mood=0.15
    anxiety_mood=2.8
    happiness_mood=8.47
    age=35.02
    height=1.89
    gender=MALE
    last_update=1.75019e+09
    goal=FUN
    working_on_goal=0
}
history=[
    well there's been a recent sell off, you probably don't want to pass this up
    oh hey
    oh there you are, want to try something
    nope!
    why not? it's fun
    i don't trust you haha
    ah man ok, well at least tell me something funny
]
