uuid=cc5a05ac-07fe-4841-9865-5f4bbcf4310c
relationship={
    me_uuid=22337de4-4fbf-465b-8c5a-05ac07feb841
    other_uuid=337de44f-bfb6-4bcc-9a05-ac07feb84198
    friendship=9
    romance=0
    trust=3.75
    random_tick=3.42
    interactions=81
    status=OTHER
    others_gender=MALE
    goal=ASK_TO_STAY
    goal_asked_for=1
}
intelligence={
    uuid=22337de4-4fbf-465b-8c5a-05ac07feb841
    goodness=9.94
    shyness=5.29
    anxiety=8.66
    silliness=9.69
    laziness=3.06
    anger=9.77
    happiness=3.14
    weirdness=0.63
    craziness=8.9
    intelligence=7.75
    anger_mood=9.94
    anxiety_mood=4.31
    happiness_mood=2
    age=90.19
    height=3.66
    gender=FEMALE
    last_update=1.74977e+09
}
history=[
    hi!
    hello
    how do you do?
    not well i'm afraid
    what a shame
    care to pass some time with an old woman?
    i don't have time
]
