uuid=ccc7fa36-682b-43ff-9e1c-737ce064ee55
relationship={
    me_uuid=da665d2c-854c-45d6-a38b-ccc7fa36682b
    other_uuid=22da665d-2c85-4cb5-9623-8bccc7fa3668
    friendship=4.42
    romance=0.1
    trust=4.5
    random_tick=6.46
    interactions=40
    status=OTHER
    others_gender=FEMALE
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=da665d2c-854c-45d6-a38b-ccc7fa36682b
    goodness=9.51
    shyness=4.3
    anxiety=9.43
    silliness=4.22
    laziness=3.67
    anger=8.46
    happiness=3.27
    weirdness=0.78
    craziness=1.59
    intelligence=9.1
    anger_mood=5.77
    anxiety_mood=1.74
    happiness_mood=8
    age=62.7
    height=3.03
    gender=MALE
    last_update=1.75017e+09
}
history=[
    I've felt sad lately, it's terrible
    oh me too, it's in the food!
    haha, it's not the food <OTHER_NPC_NAME>
    no? i could have sworn. you sure?
    aye, though i do feel a little better now
    it's the food isn't it!
    haha no. what've you been doing today?
    cracking down on wimps
    cracking down on wimps? haha, wait what did you do?
    oh you know, help understand things
]
