uuid=cefafa0f-58e8-4cbd-a176-a9a939cb5ca2
relationship={
    me_uuid=9af64d67-6d98-47a7-8efa-fa0f58e87cbd
    other_uuid=f64d676d-9867-47ce-bafa-0f58e87cbd61
    friendship=6.83
    romance=0.87
    trust=2.39
    random_tick=5.37
    interactions=26
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=9af64d67-6d98-47a7-8efa-fa0f58e87cbd
    goodness=4.14
    shyness=0.73
    anxiety=2.74
    silliness=9.29
    laziness=1.3
    anger=3.53
    happiness=5.54
    weirdness=3.37
    craziness=2.66
    intelligence=3.53
    anger_mood=2.82
    anxiety_mood=6.79
    happiness_mood=8.66
    age=35.27
    height=4.18
    gender=FEMALE
    last_update=1.75019e+09
    goal=CONTROL
    working_on_goal=1
}
history=[
    how about making me some food?
    huh?
    oh sorry, i didn't wasn't talking to you just then
    oh ok haha. hey how've you been?
    oh pretty good! i talked to <WORK_CONTACT> recently
    oh good, what'd he say
    he said he'd help us with <POLITICAL_GOAL>
]
