uuid=cf6a6642-5088-4885-9853-555fadba7d6f
relationship={
    me_uuid=be921d7d-ab86-4f6a-a642-5088c8851853
    other_uuid=52be921d-7dab-46cf-aa66-425088c88518
    friendship=3
    romance=0
    trust=9.82
    random_tick=3.3
    interactions=48
    status=OTHER
    others_gender=FEMALE
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=be921d7d-ab86-4f6a-a642-5088c8851853
    goodness=4.65
    shyness=4.82
    anxiety=8.09
    silliness=8.26
    laziness=2.07
    anger=1.54
    happiness=2.71
    weirdness=0.9
    craziness=7.67
    intelligence=5.94
    anger_mood=6.95
    anxiety_mood=8
    happiness_mood=0.55
    age=42.1
    height=3.47
    gender=MALE
    last_update=1.74977e+09
}
history=[
    hi!
    hi!
    how do you do?
    i'm dying haha
    wait what!
    only fooling
]
