uuid=d39cf2ed-e2f4-485b-a400-a1ad5151f61b
relationship={
    me_uuid=a8e8ff90-b122-439c-b2ed-e2f4f85b6400
    other_uuid=8ca8e8ff-90b1-42d3-9cf2-ede2f4f85b64
    friendship=1.78
    romance=0.3
    trust=9.94
    random_tick=6.38
    interactions=74
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=a8e8ff90-b122-439c-b2ed-e2f4f85b6400
    goodness=5.99
    shyness=0.7
    anxiety=3.51
    silliness=8.22
    laziness=5.35
    anger=0.06
    happiness=8.49
    weirdness=6.22
    craziness=8.01
    intelligence=6.7
    anger_mood=3.37
    anxiety_mood=4.06
    happiness_mood=8.81
    age=11.38
    height=0.93
    gender=FEMALE
    last_update=1.75019e+09
    goal=FUN
    working_on_goal=1
}
history=[
    what about with a beautiful old woman?
    oh do you think i'm beautiful?
    yeah i think you're beautiful!
    oh thanks <OTHER_NPC_NAME>
    yeah sure, hey do you want to make something again?
    oh ok, I'm a little tired but sure we can do that. MAKE <ART>
]
