uuid=d47951d4-3f29-4f19-a3fb-18606504c858
relationship={
    me_uuid=994eaeae-5ae1-4d98-9479-51d43f29ef19
    other_uuid=4eaeae5a-e18d-48d4-b951-d43f29ef19a3
    friendship=6
    romance=0.89
    trust=5.77
    random_tick=7.7
    interactions=49
    status=OTHER
    others_gender=MALE
    goal=GET_AWAY
    goal_asked_for=0
}
intelligence={
    uuid=994eaeae-5ae1-4d98-9479-51d43f29ef19
    goodness=9.22
    shyness=9.27
    anxiety=1.22
    silliness=1.59
    laziness=7.26
    anger=8.23
    happiness=3.9
    weirdness=9.19
    craziness=4.86
    intelligence=5.83
    anger_mood=4.22
    anxiety_mood=3
    happiness_mood=9.26
    age=46.77
    height=0.62
    gender=FEMALE
    last_update=1.74977e+09
}
history=[
    a grandpa!
    you're a grandpa?
    no but maybe I could be with you
    you will not!
    and why not!
    I may need to report you
    FIGHT
]
