uuid=dd0dd1f1-e0d6-4b29-9630-67441e034b16
relationship={
    me_uuid=408cfe68-a62f-4d0d-91f1-e0d60b29d630
    other_uuid=5e408cfe-68a6-4fdd-8dd1-f1e0d60b29d6
    friendship=7.93
    romance=0.42
    trust=6.23
    random_tick=1.05
    interactions=85
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=408cfe68-a62f-4d0d-91f1-e0d60b29d630
    goodness=8.06
    shyness=2.63
    anxiety=7.82
    silliness=3.29
    laziness=1.9
    anger=4.89
    happiness=0.3
    weirdness=8.01
    craziness=0.1
    intelligence=5.53
    anger_mood=7.62
    anxiety_mood=8.73
    happiness_mood=0.82
    age=5.61
    height=1.7
    gender=MALE
    last_update=1.75019e+09
    goal=NONE
    working_on_goal=1
}
history=[
    do you need some help?
    sure
    ok i'll help you!
    hmm, what should i have you do...
     
    how about you deliver this to <ENEMY_WORK_CONTACT> GIVE <BOMB>
]
