uuid=dd9f74b6-2427-40c5-aac3-2af8e8e763bb
relationship={
    me_uuid=a6abe0ea-781b-4d9f-b4b6-242780c56ac3
    other_uuid=abe0ea78-1bdd-4f74-b624-2780c56ac32a
    friendship=9.22
    romance=0.18
    trust=6
    random_tick=4.3
    interactions=89
    status=OTHER
    others_gender=MALE
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=a6abe0ea-781b-4d9f-b4b6-242780c56ac3
    goodness=6.57
    shyness=0.06
    anxiety=9.85
    silliness=9.5
    laziness=9.77
    anger=0.42
    happiness=5.37
    weirdness=6.02
    craziness=6.65
    intelligence=7.3
    anger_mood=3.61
    anxiety_mood=4.26
    happiness_mood=6
    age=75.9
    height=4.07
    gender=FEMALE
    last_update=1.75017e+09
}
history=[
    you're a grandpa?
    very funny <OTHER_NPC_NAME>, are you a mule?
    haha no you old hag
    how do you fare <OTHER_NPC_NAME>?
    fair enough for my own needs. though hungry
]
