uuid=e0429092-3381-4b33-a10a-6a1468304155
relationship={
    me_uuid=6a242547-8a5b-4042-9092-33814b33e10a
    other_uuid=ce6a2425-478a-4be0-8290-9233814b33e1
    friendship=5.06
    romance=0.38
    trust=1.14
    random_tick=5.7
    interactions=42
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=6a242547-8a5b-4042-9092-33814b33e10a
    goodness=2.71
    shyness=2.94
    anxiety=4.07
    silliness=4.3
    laziness=0.25
    anger=9.98
    happiness=0.25
    weirdness=9.98
    craziness=5.93
    intelligence=4.3
    anger_mood=9.71
    anxiety_mood=7.54
    happiness_mood=2.97
    age=35.9
    height=4.51
    gender=MALE
    last_update=1.75019e+09
    goal=FUN
    working_on_goal=0
}
history=[
    why do you feel sad?
    i actually don't feel sad
    why do you feel mad?
    uh, I don't feel mad
    why do you feel bad?
    what? haha ok stop it
]
