uuid=e24fc63f-0104-4deb-9c01-911994b39a89
relationship={
    me_uuid=d1f7ffc6-239b-424f-863f-01048debdc01
    other_uuid=f7ffc623-9be2-4fc6-bf01-048debdc0191
    friendship=7.83
    romance=0.47
    trust=4.55
    random_tick=2.01
    interactions=65
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=d1f7ffc6-239b-424f-863f-01048debdc01
    goodness=9.66
    shyness=2.57
    anxiety=0.5
    silliness=8.41
    laziness=6.34
    anger=9.93
    happiness=7.86
    weirdness=7.13
    craziness=5.06
    intelligence=7.13
    anger_mood=3.22
    anxiety_mood=2.01
    happiness_mood=8.1
    age=93.59
    height=3.66
    gender=IN_BETWEEN
    last_update=1.75019e+09
    goal=NONE
    working_on_goal=1
}
history=[
    oh good! haha
    oh hey litle one
    hello old one?
    hey! haha
    have you seen any good stuff for sale today?
]
