uuid=e41069b8-f068-4d86-9108-6e3696ef59f4
relationship={
    me_uuid=6c140fdc-e410-49b8-b068-9d86d1086e36
    other_uuid=2d6c140f-dce4-4069-b8f0-689d86d1086e
    friendship=5.77
    romance=0.39
    trust=0.39
    random_tick=5.74
    interactions=35
    status=PARENT
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=6c140fdc-e410-49b8-b068-9d86d1086e36
    goodness=2.9
    shyness=2.87
    anxiety=5.26
    silliness=5.59
    laziness=7.98
    anger=2.63
    happiness=5.02
    weirdness=6.01
    craziness=6.38
    intelligence=0.33
    anger_mood=2.06
    anxiety_mood=0.33
    happiness_mood=2.06
    age=29.36
    height=2.12
    gender=MALE
    last_update=1.7502e+09
    goal=NONE
    working_on_goal=0
}
history=[
    oh, i'm doing well. i see you at times here
    yeah i come here with friends sometimes
    so what do you do with your friends?
    just play or talk. you know, goof off
]
