uuid=f1e0d60b-29d6-4067-841e-034b161ef742
relationship={
    me_uuid=5e408cfe-68a6-4fdd-8dd1-f1e0d60b29d6
    other_uuid=408cfe68-a62f-4d0d-91f1-e0d60b29d630
    friendship=4.8
    romance=0.38
    trust=1.5
    random_tick=7.94
    interactions=12
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=5e408cfe-68a6-4fdd-8dd1-f1e0d60b29d6
    goodness=0.57
    shyness=8.1
    anxiety=8.09
    silliness=5.62
    laziness=1.29
    anger=8.82
    happiness=0.17
    weirdness=7.7
    craziness=4.73
    intelligence=2.26
    anger_mood=4.97
    anxiety_mood=2.5
    happiness_mood=5.37
    age=26.42
    height=1.17
    gender=FEMALE
    last_update=1.75019e+09
    goal=CONTROL
    working_on_goal=1
}
history=[
    do you need some help?
    sure
    ok i'll help you!
    hmm, what should i have you do...
     
    how about you deliver this to <ENEMY_WORK_CONTACT> GIVE <BOMB>
    uh ok what is it?
    just a present for them
    oh ok i'll do that GO_TO <ENEMY_WORK_CONTACT> GIVE <BOMB>
]
