uuid=f22c9687-808d-4c37-8fa7-5b07be947e5b
relationship={
    me_uuid=f2c08c55-f22c-4687-808d-dc370fa75b07
    other_uuid=b9f2c08c-55f2-4c96-8780-8ddc370fa75b
    friendship=8.49
    romance=5.06
    trust=6.07
    random_tick=0.73
    interactions=91
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=f2c08c55-f22c-4687-808d-dc370fa75b07
    goodness=9.74
    shyness=7.51
    anxiety=7.74
    silliness=9.83
    laziness=0.06
    anger=6.47
    happiness=6.7
    weirdness=8.17
    craziness=5.66
    intelligence=5.69
    anger_mood=8.14
    anxiety_mood=8.89
    happiness_mood=5.06
    age=81.77
    height=4.94
    gender=FEMALE
    last_update=1.75019e+09
    goal=ROB
    working_on_goal=0
}
history=[
    so how are things my daughter
    daughter haha
    oh you old fellow! where have you been all this time
    you're beautiful <OTHER_NPC_NAME>
]
