uuid=f7050d33-b364-4c88-88c9-94173cb3be6d
relationship={
    me_uuid=cfd08509-f705-4d33-b364-cc8808c99417
    other_uuid=71cfd085-09f7-450d-b3b3-64cc8808c994
    friendship=7.37
    romance=0.2
    trust=8.97
    random_tick=6.15
    interactions=20
    status=OTHER
    others_gender=MALE
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=cfd08509-f705-4d33-b364-cc8808c99417
    goodness=0.1
    shyness=2.31
    anxiety=2.06
    silliness=3.67
    laziness=5.26
    anger=1.99
    happiness=3.58
    weirdness=4.63
    craziness=6.22
    intelligence=1.59
    anger_mood=3
    anxiety_mood=7.13
    happiness_mood=4
    age=93.53
    height=4.56
    gender=MALE
    last_update=1.75017e+09
}
history=[
    why you?
    what do you mean you old fart?
    old fart! what
    yeah you old fart
]
