uuid=fafa0f58-e87c-4d61-b6a9-a939cb5ca289
relationship={
    me_uuid=f64d676d-9867-47ce-bafa-0f58e87cbd61
    other_uuid=9af64d67-6d98-47a7-8efa-fa0f58e87cbd
    friendship=6.98
    romance=0.63
    trust=8.5
    random_tick=2.26
    interactions=65
    status=OTHER
    goal=NONE
    goal_asked_for=0
}
intelligence={
    uuid=f64d676d-9867-47ce-bafa-0f58e87cbd61
    goodness=5.91
    shyness=9.34
    anxiety=9.93
    silliness=3.5
    laziness=1.45
    anger=1.98
    happiness=8.65
    weirdness=4.78
    craziness=1.53
    intelligence=8.1
    anger_mood=0.09
    anxiety_mood=7.66
    happiness_mood=4.43
    age=23.9
    height=4.63
    gender=MALE
    last_update=1.75019e+09
    goal=CONTROL
    working_on_goal=1
}
history=[
    how about making me some food?
    huh?
    oh sorry, i didn't wasn't talking to you just then
    oh ok haha. hey how've you been?
    oh pretty good! i talked to <WORK_CONTACT> recently
    oh good, what'd he say
    he said he'd help us with <POLITICAL_GOAL>
    oh great! maybe we should invite him to lunch or something
]
